// AUTO-GENERATED by scripts/build-ai-catalog.mjs — DO NOT EDIT
// Run `node scripts/build-ai-catalog.mjs` after registry changes.

export const SKILL_CATALOG = [
  {
    "skill": "accelerate-ai",
    "name": "Accelerate for AI Delivery and Reliability Agents",
    "school": "Systems & Architecture",
    "schoolName": "School of Architecture",
    "status": "—",
    "effect": "Improve engineering throughput and reliability by strengthening feedback, lowering batch risk, and shortening recovery time."
  },
  {
    "skill": "maintain-architecture",
    "name": "Architecture Maintenance",
    "school": "Systems & Architecture",
    "schoolName": "School of Architecture",
    "status": "—",
    "effect": "Review completed work for architectural quality, maintainability, feature ownership, and long-term scalability."
  },
  {
    "skill": "cross-domain-analogy-generator",
    "name": "Cross-Domain Analogy",
    "school": "Systems & Architecture",
    "schoolName": "School of Architecture",
    "status": "—",
    "effect": "Generate cross-domain analogies — break fixation by mapping problem structures to foreign fields (biology, music, traffic) and transferring insights. Use when stuck on a hard problem, when repeated attempts fail, or when local optima seem like global optima."
  },
  {
    "skill": "designing-data-intensive-applications-ai",
    "name": "Designing Data-Intensive Applications for AI Agents",
    "school": "Systems & Architecture",
    "schoolName": "School of Architecture",
    "status": "—",
    "effect": "Reason about data systems: storage choices, replication, consistency, partitioning, queues, failure modes, and operational tradeoffs."
  },
  {
    "skill": "domain-driven-design",
    "name": "Domain-Driven Design for AI Agents",
    "school": "Systems & Architecture",
    "schoolName": "School of Architecture",
    "status": "—",
    "effect": "Bounded contexts, ubiquitous language, aggregates, context maps, domain events, anti-corruption layers."
  },
  {
    "skill": "everything-as-code-conceptualizer",
    "name": "Everything-as-Code Conceptualizer",
    "school": "Systems & Architecture",
    "schoolName": "School of Architecture",
    "status": "—",
    "effect": "Codify messy human problems as pseudocode to reveal hidden assumptions, missing decisions, and edge cases."
  },
  {
    "skill": "plan-feature-architecture",
    "name": "Feature Architecture Planning",
    "school": "Systems & Architecture",
    "schoolName": "School of Architecture",
    "status": "—",
    "effect": "Decide ownership, placement, module boundaries, dependencies, and project impact before writing code."
  },
  {
    "skill": "improve-codebase-architecture",
    "name": "Improve Codebase Architecture",
    "school": "Systems & Architecture",
    "schoolName": "School of Architecture",
    "status": "—",
    "effect": "Find deepening opportunities informed by the domain language in CONTEXT.md and decisions in docs/adr/."
  },
  {
    "skill": "architecture-evolution-review",
    "name": "Mission",
    "school": "Systems & Architecture",
    "schoolName": "School of Architecture",
    "status": "—",
    "effect": "Review the repository as a living system. Detect architectural drift, feature erosion, and long-term maintenance risks."
  },
  {
    "skill": "release-it-stability",
    "name": "Release It! Stability Patterns for AI Agents",
    "school": "Systems & Architecture",
    "schoolName": "School of Architecture",
    "status": "—",
    "effect": "Circuit breakers, bulkheads, timeouts, load shedding, steady-state hygiene for production failure modes."
  },
  {
    "skill": "security-review-protocol",
    "name": "Security Review Protocol",
    "school": "Systems & Architecture",
    "schoolName": "School of Architecture",
    "status": "—",
    "effect": "Three security lenses merged: attack surface analysis, hazardous operation checking, and LLM-specific vulnerability audit."
  },
  {
    "skill": "security-threat-modeling",
    "name": "Security Threat Modeling for AI Agents",
    "school": "Systems & Architecture",
    "schoolName": "School of Architecture",
    "status": "—",
    "effect": "STRIDE threat analysis, attack-surface mapping, trust-boundary reasoning, and attacker-perspective review."
  },
  {
    "skill": "sre-error-budget",
    "name": "SRE / Error Budget Thinking for AI Agents",
    "school": "Systems & Architecture",
    "schoolName": "School of Architecture",
    "status": "—",
    "effect": "SLOs, error budgets, toil budgets, and change-velocity governance. Spend the budget on speed when healthy; freeze changes when depleted."
  },
  {
    "skill": "system-architecture-audit",
    "name": "System Architecture Audit for AI Agents",
    "school": "Systems & Architecture",
    "schoolName": "School of Architecture",
    "status": "—",
    "effect": "4-phase audit fusing Thinking in Systems, DDD, DDIA, and Release It. Reveals structural problems before they cascade."
  },
  {
    "skill": "team-topologies-ai",
    "name": "Team Topologies for Multi-Agent Software Systems",
    "school": "Systems & Architecture",
    "schoolName": "School of Architecture",
    "status": "—",
    "effect": "Stream-aligned, platform, enabling, and complicated-subsystem boundaries with explicit interaction modes."
  },
  {
    "skill": "the-goal-theory-of-constraints-ai",
    "name": "The Goal for AI Engineering Agents",
    "school": "Systems & Architecture",
    "schoolName": "School of Architecture",
    "status": "—",
    "effect": "Find the one constraint, ignore non-constraints, exploit then elevate it, repeat when it moves."
  },
  {
    "skill": "thinking-in-systems-state-machine",
    "name": "Thinking in Systems — State Machine Protocol for AI Agents",
    "school": "Systems & Architecture",
    "schoolName": "School of Architecture",
    "status": "—",
    "effect": "Model stocks, flows, delays, leverage points, and blast radius before touching the system."
  },
  {
    "skill": "vibe-coding-security-hardening",
    "name": "Vibe Coding Security Hardening",
    "school": "Systems & Architecture",
    "schoolName": "School of Architecture",
    "status": "—",
    "effect": "Systematic checklist for vulnerabilities LLMs reliably introduce: exposed secrets, missing RLS, broken auth, injection flaws, insecure defaults."
  },
  {
    "skill": "chaos-detector",
    "name": "Chaos Detector",
    "school": "Reasoning & Faithfulness",
    "schoolName": "School of Cognition",
    "status": "—",
    "effect": "Compute empirical Lyapunov exponents over token trajectories and flag when small perturbations amplify into divergent conclusions."
  },
  {
    "skill": "claim-verification-reasoning",
    "name": "Claim Verification Reasoning",
    "school": "Reasoning & Faithfulness",
    "schoolName": "School of Cognition",
    "status": "—",
    "effect": "Atomic decomposition with confidence labels and tool-grounded verification."
  },
  {
    "skill": "context-density-operator",
    "name": "Context Density Operator",
    "school": "Reasoning & Faithfulness",
    "schoolName": "School of Cognition",
    "status": "—",
    "effect": "Maximize decision-relevant information per token via hierarchical memory, on-demand detail expansion, and redundant-context pruning."
  },
  {
    "skill": "context-rot-pruner",
    "name": "Context Rot Pruner",
    "school": "Reasoning & Faithfulness",
    "schoolName": "School of Cognition",
    "status": "—",
    "effect": "Apply exponential decay to context messages so old, unreferenced content gets pruned before the context window overflows."
  },
  {
    "skill": "cot-pruning-reasoning",
    "name": "CoT Pruning Reasoning",
    "school": "Reasoning & Faithfulness",
    "schoolName": "School of Cognition",
    "status": "—",
    "effect": "Two-pass prune retains only the steps that move the answer (coarse step-level, then fine token-level)."
  },
  {
    "skill": "faithfulness-aware-reasoning",
    "name": "Faithfulness-Aware Reasoning",
    "school": "Reasoning & Faithfulness",
    "schoolName": "School of Cognition",
    "status": "—",
    "effect": "Detect and prevent faithfulness hallucinations where claims aren't logically entailed by the premises."
  },
  {
    "skill": "hallucination-anchor-chain",
    "name": "Hallucination Anchor Chain",
    "school": "Reasoning & Faithfulness",
    "schoolName": "School of Cognition",
    "status": "—",
    "effect": "Anchor every factual claim to a verified source — unanchored claims are hidden. Builds a verifiable chain of evidence. Use when accuracy matters in research, code generation with external APIs, multi-step reasoning where errors compound, or any domain where wrong facts cause harm."
  },
  {
    "skill": "prism",
    "name": "Prism",
    "school": "Reasoning & Faithfulness",
    "schoolName": "School of Cognition",
    "status": "—",
    "effect": "Force numeric confidence on each claim, compress to its essence, then verify the compression reconstructs the original."
  },
  {
    "skill": "reasoning-integrity-chain",
    "name": "Reasoning Integrity Chain for AI Agents",
    "school": "Reasoning & Faithfulness",
    "schoolName": "School of Cognition",
    "status": "—",
    "effect": "Escalating 4-phase verification chain: faithfulness, claims, contradiction, selective halt."
  },
  {
    "skill": "reasoning-verification-hybrid",
    "name": "Reasoning Verification Hybrid",
    "school": "Reasoning & Faithfulness",
    "schoolName": "School of Cognition",
    "status": "—",
    "effect": "Claim verification, backward contradiction, and calibrated confidence."
  },
  {
    "skill": "selective-halt-reasoning",
    "name": "Selective Halt Reasoning",
    "school": "Reasoning & Faithfulness",
    "schoolName": "School of Cognition",
    "status": "—",
    "effect": "Monitor for semantic stabilization and halt early when consecutive steps converge on equivalent conclusions."
  },
  {
    "skill": "self-contradiction-trap",
    "name": "Self-Contradiction Trap",
    "school": "Reasoning & Faithfulness",
    "schoolName": "School of Cognition",
    "status": "—",
    "effect": "Maintain a belief store of claims made during a session. Detect contradictions and force resolution before continuing."
  },
  {
    "skill": "token-budget-operator",
    "name": "Token Budget Operator",
    "school": "Reasoning & Faithfulness",
    "schoolName": "School of Cognition",
    "status": "—",
    "effect": "Orchestrate context compression, CoT pruning, selective halting, and SOP capture in sequence."
  },
  {
    "skill": "active-inference-agent",
    "name": "Active Inference Agent",
    "school": "MCP Servers",
    "schoolName": "School of Conduits",
    "status": "—",
    "effect": "MCP server implementing a practical Active Inference agent based on Friston's Free Energy Principle."
  },
  {
    "skill": "evolutionary-tool-composer",
    "name": "Evolutionary Tool Composer",
    "school": "MCP Servers",
    "schoolName": "School of Conduits",
    "status": "—",
    "effect": "MCP server that runs an evolutionary algorithm to discover and optimize agent tool chains, prompt strategies, and code solutions."
  },
  {
    "skill": "agent-memory-hygiene",
    "name": "Agent Memory Hygiene for AI Agents",
    "school": "Agent Orchestration",
    "schoolName": "School of Confluence",
    "status": "—",
    "effect": "Control what is stored, retrieved, trusted, and discarded to avoid stale-context actions."
  },
  {
    "skill": "agentic-design-patterns-orchestrator-state-machine",
    "name": "Agentic Patterns Orchestrator — State Machine Protocol for AI Agents",
    "school": "Agent Orchestration",
    "schoolName": "School of Confluence",
    "status": "—",
    "effect": "Enforce a phased workflow with explicit gates between classify, plan, execute, reflect, and verify."
  },
  {
    "skill": "agentic-design-patterns-orchestrator",
    "name": "Agentic Patterns Orchestrator for AI Agents",
    "school": "Agent Orchestration",
    "schoolName": "School of Confluence",
    "status": "—",
    "effect": "Adopt pattern-based orchestration with planning, routing, reflection, and recovery."
  },
  {
    "skill": "jury",
    "name": "Jury",
    "school": "Agent Orchestration",
    "schoolName": "School of Confluence",
    "status": "—",
    "effect": "Spawn parallel perspectives with conflicting goals, force them to engage, output a conflict graph that reveals what actually matters."
  },
  {
    "skill": "monte-carlo-tree-search",
    "name": "Monte Carlo Tree Search for AI Agents",
    "school": "Agent Orchestration",
    "schoolName": "School of Confluence",
    "status": "—",
    "effect": "Allocate search effort to branches that earn it through probes and scoring."
  },
  {
    "skill": "navigator",
    "name": "Navigator",
    "school": "Agent Orchestration",
    "schoolName": "School of Confluence",
    "status": "—",
    "effect": "Scout reads code, Thought-Retriever stores the reasoning trail so future sessions resume from where you stopped."
  },
  {
    "skill": "octopus",
    "name": "Octopus",
    "school": "Agent Orchestration",
    "schoolName": "School of Confluence",
    "status": "—",
    "effect": "Coordinate parallel sub-agents with bounded concurrency — define shared contracts, delegate with auto-healing arms, retract on failure. Use when 3+ workstreams share a contract and parallel speedup beats coordination overhead."
  },
  {
    "skill": "pre-flight-intent-verification",
    "name": "Pre-Flight Intent Verification",
    "school": "Agent Orchestration",
    "schoolName": "School of Confluence",
    "status": "—",
    "effect": "Surface the critical assumption, crystallize intent into testable spec, ground facts before acting."
  },
  {
    "skill": "rashomon-triad-hybrid",
    "name": "Rashomon-Triad Hybrid",
    "school": "Agent Orchestration",
    "schoolName": "School of Confluence",
    "status": "—",
    "effect": "Parallel perspectives with conflicting goals run independent abductive-deductive-inductive cycles, then argue via attack graph."
  },
  {
    "skill": "scout",
    "name": "Scout",
    "school": "Agent Orchestration",
    "schoolName": "School of Confluence",
    "status": "—",
    "effect": "Scout context — a fast sub-agent reads files and returns only distilled relevant context, saving tokens and reducing distraction for the main model. Use when the codebase is large, you need scoped findings rather than raw file dumps, or the main task needs file context you don't already have."
  },
  {
    "skill": "separation-of-concerns",
    "name": "Separation of Concerns for AI Agent Orchestration",
    "school": "Agent Orchestration",
    "schoolName": "School of Confluence",
    "status": "—",
    "effect": "Keep planning, diagnosis, observation, and execution phases intellectually isolated."
  },
  {
    "skill": "socratic-clarification",
    "name": "Socratic Clarification Protocol for AI Agents",
    "school": "Agent Orchestration",
    "schoolName": "School of Confluence",
    "status": "—",
    "effect": "Surface the most critical hidden assumption before committing to execution."
  },
  {
    "skill": "sop-evolution-memory",
    "name": "SOP Evolution Memory",
    "school": "Agent Orchestration",
    "schoolName": "School of Confluence",
    "status": "—",
    "effect": "Distill trajectories into reusable Standard Operating Procedures (SOPs) after repeated successes on a class of tasks."
  },
  {
    "skill": "subagent-composer",
    "name": "Sub-Agent Composer — High-Context Delegation",
    "school": "Agent Orchestration",
    "schoolName": "School of Confluence",
    "status": "—",
    "effect": "Compose high-context sub-agent briefs with skill loading, explicit boundaries, success criteria, and stop rules."
  },
  {
    "skill": "subagent-laws",
    "name": "Sub-Agent Laws",
    "school": "Agent Orchestration",
    "schoolName": "School of Confluence",
    "status": "—",
    "effect": "Standing behavioral constraints every sub-agent must follow. Enforce scope discipline, test integrity, and communication standards."
  },
  {
    "skill": "thought-retriever-coppermind",
    "name": "Thought-Retriever with Coppermind",
    "school": "Agent Orchestration",
    "schoolName": "School of Confluence",
    "status": "—",
    "effect": "Store intermediate reasoning as retrievable thoughts in the Coppermind memory layers."
  },
  {
    "skill": "weak-link-detection-multi-agent",
    "name": "Weak-Link Detection for Multi-Agent Systems",
    "school": "Agent Orchestration",
    "schoolName": "School of Confluence",
    "status": "—",
    "effect": "Identify and isolate the weakest reasoning chain in multi-agent outputs before aggregation."
  },
  {
    "skill": "llm-pre-push-review",
    "name": "1. Run existing tests",
    "school": "Software Development",
    "schoolName": "School of Crafting",
    "status": "—",
    "effect": "Checklist and protocol for catching systematic LLM coding failures: overcorrection, hallucinated logic, silent vulnerabilities, missing edge cases."
  },
  {
    "skill": "pre-deployment-gate",
    "name": "1. Tests",
    "school": "Software Development",
    "schoolName": "School of Crafting",
    "status": "—",
    "effect": "Complete pre-deployment checklist merging LLM Pre-Push Review with Vibe Coding Security Hardening."
  },
  {
    "skill": "api-design-backward-compatibility",
    "name": "API Design and Backward Compatibility",
    "school": "Software Development",
    "schoolName": "School of Crafting",
    "status": "—",
    "effect": "Contract-first design and additive-only change discipline for evolving APIs without breaking clients."
  },
  {
    "skill": "api-surface-anchoring",
    "name": "API Surface Anchoring",
    "school": "Software Development",
    "schoolName": "School of Crafting",
    "status": "—",
    "effect": "Verify every external API call against current docs to prevent hallucinated APIs."
  },
  {
    "skill": "code-knowledge-graph-mcp",
    "name": "Code Knowledge Graph MCP",
    "school": "Software Development",
    "schoolName": "School of Crafting",
    "status": "—",
    "effect": "MCP server with structured symbol and call-graph queries. Navigate code by structure, not by string search."
  },
  {
    "skill": "code-review-excellence",
    "name": "Code Review Excellence",
    "school": "Software Development",
    "schoolName": "School of Crafting",
    "status": "—",
    "effect": "Provide constructive feedback, catch bugs early, and foster knowledge sharing while maintaining team morale."
  },
  {
    "skill": "codebase-divide-conquer-search",
    "name": "Codebase Divide-and-Conquer Search",
    "school": "Software Development",
    "schoolName": "School of Crafting",
    "status": "—",
    "effect": "Divide a large codebase into manageable chunks and search each systematically."
  },
  {
    "skill": "coordinated-change",
    "name": "Coordinated Change",
    "school": "Software Development",
    "schoolName": "School of Crafting",
    "status": "—",
    "effect": "Ensure consistency when a fix or feature requires touching 2+ files that must stay consistent."
  },
  {
    "skill": "critical-system-interrogation",
    "name": "Critical System Interrogation",
    "school": "Software Development",
    "schoolName": "School of Crafting",
    "status": "—",
    "effect": "Stress-test critical system paths (auth pipelines, payment flows, data validation) for correctness, race conditions, security flaws, and architectural integrity."
  },
  {
    "skill": "dev-diagnostics-mcp",
    "name": "Dev Diagnostics MCP",
    "school": "Software Development",
    "schoolName": "School of Crafting",
    "status": "—",
    "effect": "Run diagnostics across multiple tools (eslint, tsc, vitest, pytest, biome, ruff) and compare before/after for contamination."
  },
  {
    "skill": "lint-battalion",
    "name": "ESLint",
    "school": "Software Development",
    "schoolName": "School of Crafting",
    "status": "—",
    "effect": "Batch-process 50+ linter errors as a bulk remediation problem, not 50 separate decisions."
  },
  {
    "skill": "git-surgery",
    "name": "Identify the detached commits",
    "school": "Software Development",
    "schoolName": "School of Crafting",
    "status": "—",
    "effect": "Recover from local git disasters: detached HEAD, botched rebase, accidental commits, merge conflicts."
  },
  {
    "skill": "native-data-fetching",
    "name": "Native Data Fetching",
    "school": "Software Development",
    "schoolName": "School of Crafting",
    "status": "—",
    "effect": "Covers fetch API, React Query, SWR, error handling, caching, offline support, and Expo Router data loaders."
  },
  {
    "skill": "review-changes",
    "name": "Review Changes",
    "school": "Software Development",
    "schoolName": "School of Crafting",
    "status": "—",
    "effect": "Structured review checklist for evaluating code changes systematically."
  },
  {
    "skill": "review-ladder-plus",
    "name": "Review Ladder Plus",
    "school": "Software Development",
    "schoolName": "School of Crafting",
    "status": "—",
    "effect": "Multi-agent code review ladder for production-grade QA: security, auth, data, concurrency."
  },
  {
    "skill": "refactor-safely",
    "name": "Safe Refactor",
    "school": "Software Development",
    "schoolName": "School of Crafting",
    "status": "—",
    "effect": "Characterization testing to capture existing behavior, then bounded changes with immediate verification."
  },
  {
    "skill": "super-review-typescript",
    "name": "Super Review TypeScript",
    "school": "Software Development",
    "schoolName": "School of Crafting",
    "status": "—",
    "effect": "Targets the five LLM-specific failure modes: security vulnerabilities, hallucinated APIs, logic errors, type-safety violations, architectural decay."
  },
  {
    "skill": "verified-api-workflow",
    "name": "Verified API Workflow",
    "school": "Software Development",
    "schoolName": "School of Crafting",
    "status": "—",
    "effect": "Every external API call must be traceable to a doc you actually checked."
  },
  {
    "skill": "verified-synthesize",
    "name": "Verified Code Synthesizer",
    "school": "Software Development",
    "schoolName": "School of Crafting",
    "status": "—",
    "effect": "Verify code correctness through formal Dafny specifications — given a natural language spec, produce provably correct code with pre/postconditions and loop invariants. Use for critical bugs in security, memory safety, or financial calculations; pre-refactor spec locking; or API contracts across module boundaries."
  },
  {
    "skill": "verify-before-integrate",
    "name": "Verify Before Integrate",
    "school": "Software Development",
    "schoolName": "School of Crafting",
    "status": "—",
    "effect": "Verify the actual system behavior rather than matching abstract terminology when integrating research or external docs."
  },
  {
    "skill": "philosophy-of-software-design-state-machine",
    "name": "A Philosophy of Software Design — State Machine Protocol for AI Agents",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Design deeper modules, avoid shallow abstraction sprawl, declare unknowns and blast radius, bound change scope."
  },
  {
    "skill": "blueprint",
    "name": "Blueprint",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Blueprint a messy problem into formal schema — types, operations, events, constraints — so contradictions, gaps, and hidden assumptions surface as bugs. Use when scope keeps expanding, stakeholders talk past each other, or informal requirements need precision."
  },
  {
    "skill": "checklist-manifesto",
    "name": "Checklist Manifesto — State Machine Protocol for AI Agents",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Build the smallest useful checklist for high-stakes procedures, gate execution on checklist completion, stop cleanly and escalate if it cannot be cleared."
  },
  {
    "skill": "cognitive-friction-governor",
    "name": "Cognitive Friction Governor",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Assign deliberation budgets to tasks; each reasoning step consumes friction; budget exhausted forces decision."
  },
  {
    "skill": "context-budget-operator",
    "name": "Estimate token cost of files",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Track token budget, classify information needs, compress aggressively, and decide breadth-vs-depth based on remaining runway."
  },
  {
    "skill": "how-to-solve-it-analogy",
    "name": "How to Solve It — Analogy",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Apply analogy to a problem — find a structurally related solved problem, map the correspondence, transfer the solution, adapt it. Use when a problem resembles one solved in another domain, when a design pattern from elsewhere seems applicable, or when brute-force analysis needs a structural guide."
  },
  {
    "skill": "how-to-solve-it-state-machine",
    "name": "How to Solve It — State Machine Protocol for AI Agents",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Frame the problem, gather evidence, explore via hypothesis, plan, reflect. Designed to prevent premature coding."
  },
  {
    "skill": "intent-specification-protocol",
    "name": "Intent Specification Protocol",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Crystallize vague coding requests into precise, testable specifications before writing any code. Prevents the Intent-Behavior Mirroring Effect."
  },
  {
    "skill": "iterative-spec-authoring",
    "name": "Iterative Spec Authoring",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Author a detailed technical spec grounded in research, refine through up to 3 judge-LLM review cycles, then present to the user for final approval."
  },
  {
    "skill": "keyword-agnostic-logic-locator",
    "name": "Keyword-Agnostic Logic Locator",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Find code by structural relationships and logical queries via a Datalog-style knowledge graph over call graphs, data flows, and type hierarchies."
  },
  {
    "skill": "legacy-rescue-protocol",
    "name": "Legacy Rescue Protocol",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Fuse of Working Effectively with Legacy Code + Refactoring State Machine. Characterize legacy behavior, create seams, then transform in bounded slices with anti-loop protection."
  },
  {
    "skill": "long-task-survival-kit",
    "name": "Long Task Survival Kit",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Recurring checkpoint protocol that prevents agent decay on complex tasks: context overflow, failure spirals, and hallucinated facts."
  },
  {
    "skill": "ooda-loop-state-machine",
    "name": "OODA Loop — State Machine Protocol for AI Agents",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Observe, Orient, Decide, Act, Loop. Maintains decision tempo against an environment that shifts between every move."
  },
  {
    "skill": "pdca-deming",
    "name": "PDCA / Shewhart Cycle — State Machine Protocol for AI Agents",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Use when improving a process through a measurement-anchored cycle — plan with a measurable prediction, do, check actual vs predicted, then standardize or escalate. Do not standardize what was not measured."
  },
  {
    "skill": "plan-with-judge",
    "name": "Plan with Judge",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Create an implementation plan in JSONL format, then iteratively improve it using a stronger model as a judge until approved."
  },
  {
    "skill": "process-reward-model-protocol",
    "name": "Process Reward Model Protocol",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Self-assign process rewards per step and backtrack when cumulative reward drops below threshold."
  },
  {
    "skill": "refactoring-state-machine",
    "name": "Refactoring — State Machine Protocol for AI Agents",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Characterize behavior, transform in bounded slices, re-test. Stops refactor loops."
  },
  {
    "skill": "requirement-crystallization-protocol",
    "name": "Requirement Crystallization Protocol",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Surface the critical assumption, then crystallize vague requests into locked, testable specs before coding begins."
  },
  {
    "skill": "retrospective",
    "name": "Retrospective — After-Action Learning from Real Outcomes",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "After an incident, shipped feature, or completed project, systematically learn from what happened."
  },
  {
    "skill": "speculative-drafting-verification",
    "name": "Speculative Drafting with Verification",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Generate multiple solution branches in parallel, verify each against hard constraints, select the best."
  },
  {
    "skill": "speculative-exploration-protocol",
    "name": "Speculative Exploration Protocol for AI Agents",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Branch into N candidates, score with process rewards, prune low-reward branches, verify the best against hard constraints."
  },
  {
    "skill": "split-large-files",
    "name": "Split Large Files — Boundary-Driven Extraction Protocol",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Split large files along change boundaries, not line counts. Investigate before extracting, require strong architectural signals."
  },
  {
    "skill": "step-level-verification-protocol",
    "name": "Step-Level Verification Protocol",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Verify each step before proceeding so a wrong step doesn't cascade into a chain of unjustified conclusions."
  },
  {
    "skill": "structured-feature-planning",
    "name": "Structured Feature Planning",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Read files, search for patterns, self-review twice, then execute. Never hallucinate when confused."
  },
  {
    "skill": "summarize",
    "name": "Summarize — Emergency Stop + Handoff Report",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Emergency stop + perfect handoff report so the next agent loses nothing."
  },
  {
    "skill": "pragmatic-programmer-state-machine",
    "name": "The Pragmatic Programmer — State Machine Protocol for AI Agents",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Bounded changes, reversible choices, automation over repeated toil, root-cause fixes over symptom patches."
  },
  {
    "skill": "toyota-kata-state-machine",
    "name": "Toyota Kata — State Machine Protocol for Continuous-Improvement AI Agents",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Frame target, analyze current, attack one obstacle at a time, run a PDCA experiment, learn, repeat."
  },
  {
    "skill": "trajectory-guard",
    "name": "Trajectory Guard — Detect and Recover from Failure Spirals",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Detect agent failure spirals — repetitive loops, specification drift, and stuck trajectories — and forcibly redirect strategy."
  },
  {
    "skill": "assumption-grounding",
    "name": "Verify a batch of assumptions from a file",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "State every assumption explicitly, verify with the cheapest possible check, and only proceed on confirmation."
  },
  {
    "skill": "working-effectively-with-legacy-code-state-machine",
    "name": "Working Effectively with Legacy Code — State Machine Protocol for AI Agents",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "Characterize legacy behavior, create seams, transform in bounded slices with anti-loop protection."
  },
  {
    "skill": "zero-defect-protocol",
    "name": "Zero-Defect Protocol",
    "school": "Execution & Improvement",
    "schoolName": "School of Execution",
    "status": "—",
    "effect": "14-phase protocol for mission-critical features: data contracting, invariant mapping, red-team critique, pre-mortem before any code is written."
  },
  {
    "skill": "adversarial-review",
    "name": "Adversarial Review",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Stress-test proposals against a separate adversarial subagent. Tool-mediated review with no prior investment."
  },
  {
    "skill": "advocatus-diaboli",
    "name": "Advocatus Diaboli — Adversarial Review via Separate Sub-Agent",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Stress-test a proposal, plan, code change, or decision against a separate adversarial sub-agent before committing."
  },
  {
    "skill": "bayesian-updating",
    "name": "Bayesian Belief Updating for AI Agents",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Maintain explicit priors updated by likelihood, avoiding over- and under-reaction to new evidence."
  },
  {
    "skill": "cognitive-bias-auditor",
    "name": "Cognitive Bias Auditor",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Explicit audit framework covering the 9 most common cognitive biases in agents."
  },
  {
    "skill": "cognitive-bias-checklist",
    "name": "Cognitive Bias Checklist for AI Agents",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Explicit checklist to catch bias contamination before finalizing slow-mode recommendations."
  },
  {
    "skill": "counterfactual-policy-testing",
    "name": "Counterfactual Policy Testing",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Compare a decision against null, opposite, and partial counterfactuals before committing."
  },
  {
    "skill": "explore-vs-exploit-state-machine",
    "name": "Explore vs Exploit — State Machine Protocol for AI Agents",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Explicit explore/exploit protocol with diminishing-returns stopping rule."
  },
  {
    "skill": "explore-vs-exploit",
    "name": "Explore vs Exploit for AI Agents",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Deliberate explore/exploit choice instead of defaulting to either extreme."
  },
  {
    "skill": "failure-analysis-protocol",
    "name": "Failure Analysis Protocol",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Three failure lenses merged: invert success, narrate specific failures, trace cascading consequences."
  },
  {
    "skill": "first-principles",
    "name": "First Principles Thinking for AI Agents",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Decompose to axiomatic foundations and reason upward from what must be true."
  },
  {
    "skill": "inversion-mental-model-state-machine",
    "name": "Inversion — State Machine Protocol for AI Agents",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Enforce failure-mode mapping and guardrail derivation before recommending success paths."
  },
  {
    "skill": "inversion-mental-model",
    "name": "Inversion for AI Agents",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Model failure paths before recommending the success path."
  },
  {
    "skill": "metacognitive-monitoring",
    "name": "Metacognitive Monitoring — Know When You Don't Know",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Explicit KEEP/WITHDRAW decisions tied to measured withdrawal delta."
  },
  {
    "skill": "occams-razor",
    "name": "Occam's Razor for AI Agents",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Favor the simplest sufficient explanation or solution. Try the simplest thing that fits the evidence before escalating."
  },
  {
    "skill": "pre-mortem",
    "name": "Pre-Mortem",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Run a pre-mortem on a plan — assume failure has already happened, narrate backward to root causes, convert risks to guardrails. Use when finalizing a high-stakes plan, when consensus creates optimism blindness, or before a rollout, migration, or launch that is hard to reverse."
  },
  {
    "skill": "pre-mortem-state-machine",
    "name": "Pre-Mortem — State Machine Protocol for AI Agents",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Pre-mortem protocol with artifact gating, narrative failure modeling, and risk-adjusted plan revision."
  },
  {
    "skill": "problem-mode-router-cynefin",
    "name": "Problem-Mode Router (Cynefin)",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Cynefin-based routing before solving the problem. Classify the problem type before deciding how to solve it."
  },
  {
    "skill": "problem-mode-router-cynefin-state-machine",
    "name": "Problem-Mode Router (Cynefin) — State Machine Protocol for AI Agents",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Enforce Cynefin domain classification as a hard gate before any tool use or execution."
  },
  {
    "skill": "recognition-primed-triage",
    "name": "Recognition-Primed Triage",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Pattern recognition, mental simulation, and immediate next move under incomplete information."
  },
  {
    "skill": "recognition-primed-triage-state-machine",
    "name": "Recognition-Primed Triage — State Machine Protocol for AI Agents",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Gated incident-response protocol with simulation and bounded first action."
  },
  {
    "skill": "reference-class-forecasting",
    "name": "Reference Class Forecasting for AI Agents",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Anchor to similar past projects before reasoning from the specifics."
  },
  {
    "skill": "second-order-thinking",
    "name": "Second-Order Thinking for AI Agents",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Chain consequences past first-order until the system-level outcome is clear."
  },
  {
    "skill": "six-thinking-hats",
    "name": "Six Thinking Hats for AI Agents",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Separate fact, intuition, caution, optimism, creativity, and process into six discrete rounds."
  },
  {
    "skill": "steelmanning",
    "name": "Steelmanning for AI Agents",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Construct the strongest opposing case before committing to a recommendation."
  },
  {
    "skill": "task-intake-protocol",
    "name": "Task Intake Protocol",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Universal preflight gate: classify the problem, set the evidence bar, take the first action."
  },
  {
    "skill": "kahneman-thinking-fast-slow-software-agent",
    "name": "Thinking Fast and Slow for Software Engineering Agents",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Switch between fast pattern recognition and slow deliberation as stakes demand."
  },
  {
    "skill": "thoroughness-check-etto",
    "name": "Thoroughness Check (ETTO Principle) for AI Agents",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Classify the efficiency-vs-thoroughness balance before acting."
  },
  {
    "skill": "thoroughness-check-etto-state-machine",
    "name": "Thoroughness Check (ETTO) — State Machine Protocol for AI Agents",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Gate ETTO classification into executable controls on rigor, evidence, and tools."
  },
  {
    "skill": "unsafe-control-actions-hazard-analysis",
    "name": "Unsafe Control Actions / Hazard Analysis",
    "school": "Judgment & Decision-Making",
    "schoolName": "School of Judgment",
    "status": "—",
    "effect": "Analyze how a control action could become unsafe before recommending or performing it."
  },
  {
    "skill": "e2e-crosscheck",
    "name": "E2E Cross-Check Protocol",
    "school": "Testing & Measurement",
    "schoolName": "School of Measurement",
    "status": "—",
    "effect": "Bidirectional audit between E2E test selectors/assertions and source code. Reconciles every test identifier, text assertion, and navigation route."
  },
  {
    "skill": "e2e-testing-philosophy-and-architecture",
    "name": "E2E Testing Philosophy & Architecture — Reference",
    "school": "Testing & Measurement",
    "schoolName": "School of Measurement",
    "status": "—",
    "effect": "Reference for E2E testing mindset, architecture, and strategy: testing epistemology, 3-layer BDR architecture, risk-based prioritization, data realism principles."
  },
  {
    "skill": "empirical-justification",
    "name": "Empirical Justification",
    "school": "Testing & Measurement",
    "schoolName": "School of Measurement",
    "status": "—",
    "effect": "Gather empirical evidence — usage telemetry, A/B results, regression counts — to justify retiring, refining, or promoting a skill."
  },
  {
    "skill": "skill-ab-evaluation",
    "name": "Good: per-run copied snapshot",
    "school": "Testing & Measurement",
    "schoolName": "School of Measurement",
    "status": "—",
    "effect": "A/B evaluate any GrimoireStack skill against a baseline using isolated subagents, 5 trials each, and an objective rubric."
  },
  {
    "skill": "mobile-e2e-testing-enterprise-guide",
    "name": "Mobile E2E Testing: The Hunter's Mindset",
    "school": "Testing & Measurement",
    "schoolName": "School of Measurement",
    "status": "—",
    "effect": "Hunter's mindset for mobile E2E testing: what to test, how to catch real bugs, and avoid traps."
  },
  {
    "skill": "e2e-test-premortem",
    "name": "Premortem: E2E Test Audit Protocol",
    "school": "Testing & Measurement",
    "schoolName": "School of Measurement",
    "status": "—",
    "effect": "Premortem for E2E test changes. Audit coverage gaps, data realism, failure-mode coverage, and assertion quality."
  },
  {
    "skill": "test-driven-development",
    "name": "Test-Driven Development",
    "school": "Testing & Measurement",
    "schoolName": "School of Measurement",
    "status": "—",
    "effect": "Red-green-refactor loop. Write the test first, watch it fail, write the minimal fix, then refactor."
  },
  {
    "skill": "local-llm-tooling",
    "name": "Local LLM Tooling Skill",
    "school": "Mlops",
    "schoolName": "School of Mlops",
    "status": "—",
    "effect": "Run, prompt, and extract structured output from local LLMs (e.g., Ollama, llama.cpp)."
  },
  {
    "skill": "bounded-self-revision",
    "name": "Bounded Self-Revision",
    "school": "Output Quality",
    "schoolName": "School of Refinement",
    "status": "—",
    "effect": "Capped self-critique passes that terminate on improvement or budget exhaustion."
  },
  {
    "skill": "cognitive-load-operator-state-machine",
    "name": "Cognitive Load Operator — State Machine Protocol for AI Agents",
    "school": "Output Quality",
    "schoolName": "School of Refinement",
    "status": "—",
    "effect": "Inspect complexity and replace high-load structures with lower-load equivalents."
  },
  {
    "skill": "compression-as-understanding",
    "name": "Compression-as-Understanding",
    "school": "Output Quality",
    "schoolName": "School of Refinement",
    "status": "—",
    "effect": "Compress to the shortest representation and test whether it reconstructs the original."
  },
  {
    "skill": "documentation-craft",
    "name": "Documentation Craft — Structured Technical Writing",
    "school": "Output Quality",
    "schoolName": "School of Refinement",
    "status": "—",
    "effect": "Multi-phase pipeline from outline to verified explanation, audience-driven and source-grounded."
  },
  {
    "skill": "feynman-technique",
    "name": "Feynman Technique for AI Agents",
    "school": "Output Quality",
    "schoolName": "School of Refinement",
    "status": "—",
    "effect": "Explain from scratch in plain language and identify where the explanation breaks."
  },
  {
    "skill": "large-documentation-navigation",
    "name": "Large Documentation Navigation",
    "school": "Output Quality",
    "schoolName": "School of Refinement",
    "status": "—",
    "effect": "Layered navigation driven by user situation rather than category labels."
  },
  {
    "skill": "mece-pyramid-principle",
    "name": "MECE / Pyramid Principle for AI Agents",
    "school": "Output Quality",
    "schoolName": "School of Refinement",
    "status": "—",
    "effect": "Enforce mutually exclusive, collectively exhaustive categories under a single governing thought."
  },
  {
    "skill": "self-verify-pipeline",
    "name": "Self Verify Pipeline",
    "school": "Output Quality",
    "schoolName": "School of Refinement",
    "status": "—",
    "effect": "Escalating verification chain of bounded revision, claim decomposition, and tool-grounded critique."
  },
  {
    "skill": "self-consistency",
    "name": "Self-Consistency Check for AI Agents",
    "school": "Output Quality",
    "schoolName": "School of Refinement",
    "status": "—",
    "effect": "Generate independent reasoning paths and check whether they converge."
  },
  {
    "skill": "stakeholder-communication",
    "name": "Stakeholder Communication and Uncertainty Calibration",
    "school": "Output Quality",
    "schoolName": "School of Refinement",
    "status": "—",
    "effect": "Calibrate certainty, separate fact from inference, avoid overpromising or undue alarm."
  },
  {
    "skill": "tool-interactive-critic",
    "name": "Tool-Interactive Critic",
    "school": "Output Quality",
    "schoolName": "School of Refinement",
    "status": "—",
    "effect": "External tools critique the output before it is trusted."
  },
  {
    "skill": "tree-of-thoughts",
    "name": "Tree of Thoughts for AI Agents",
    "school": "Output Quality",
    "schoolName": "School of Refinement",
    "status": "—",
    "effect": "Branch, evaluate, and prune candidate solutions before committing."
  },
  {
    "skill": "abductive-first-debugging",
    "name": "Abductive-First Debugging",
    "school": "Debugging",
    "schoolName": "School of Remediation",
    "status": "—",
    "effect": "Generate multiple competing hypotheses, select the one that best explains all observed symptoms."
  },
  {
    "skill": "simulate-instrumentation",
    "name": "Before (buggy)",
    "school": "Debugging",
    "schoolName": "School of Remediation",
    "status": "—",
    "effect": "Auto-insert temporary print/logging statements at key points in the code, run the failing test, and feed the captured runtime state to the LLM."
  },
  {
    "skill": "bisect-debugging",
    "name": "Bisect Debugging",
    "school": "Debugging",
    "schoolName": "School of Remediation",
    "status": "—",
    "effect": "Isolate the exact commit that introduced a bug using binary search through git history."
  },
  {
    "skill": "bug-inquisition",
    "name": "Bug Inquisition",
    "school": "Debugging",
    "schoolName": "School of Remediation",
    "status": "—",
    "effect": "Deep root-cause debugging with mandatory context-gathering. Fuses root-cause analysis, specter, diagnose, debug-to-fix-pipeline, occam-root-cause, and reasoning-integrity-chain into one sequential protocol."
  },
  {
    "skill": "bug-inquisition-conquest",
    "name": "Bug Inquisition — Conquest Mode",
    "school": "Debugging",
    "schoolName": "School of Remediation",
    "status": "—",
    "effect": "Run conquest-mode debugging — ultra-heavy root-cause analysis with ongoing adversarial interrogation, evidence-ledger tracking, pre-mortem on every fix, and confidence-gated phase transitions. Use for the hardest bugs where surface debugging has failed, for intermittent or environment-specific bugs, or when the cost of a wrong fix exceeds the cost of thorough investigation."
  },
  {
    "skill": "explore-codebase",
    "name": "Codebase Walk",
    "school": "Debugging",
    "schoolName": "School of Remediation",
    "status": "—",
    "effect": "Structured exploration with progressive deepening: module structure → file roles → symbol resolution."
  },
  {
    "skill": "debug-issue",
    "name": "Debug Issue",
    "school": "Debugging",
    "schoolName": "School of Remediation",
    "status": "—",
    "effect": "Force the reproduce → isolate → fix → verify cycle. Graph-powered code navigation traces issues through the system along dataflow edges."
  },
  {
    "skill": "debug-subagent",
    "name": "Debug Subagent",
    "school": "Debugging",
    "schoolName": "School of Remediation",
    "status": "—",
    "effect": "Gate debugging behind a dedicated subagent — consult it before any code edit. Wraps debugger complexity behind natural-language queries. Use when the fix is not immediately obvious from the error, for multi-file bugs needing runtime state inspection, or when static analysis hasn't revealed the root cause."
  },
  {
    "skill": "debug-to-fix-pipeline",
    "name": "Debug-to-Fix Pipeline for AI Agents",
    "school": "Debugging",
    "schoolName": "School of Remediation",
    "status": "—",
    "effect": "6-phase pipeline that increases evidence quality each phase while cutting token waste. Sequences data → hypothesis → isolation → exploitation → repair → verification. Use when debugging is stalling, multi-file bugs need runtime state, or first patch attempt failed."
  },
  {
    "skill": "environment-recovery",
    "name": "Environment Recovery",
    "school": "Debugging",
    "schoolName": "School of Remediation",
    "status": "—",
    "effect": "Diagnose and fix broken development environments — missing tools, wrong versions, corrupted caches, full disks, permission drift, and dependency hell. The skill every other debugging skill assumes."
  },
  {
    "skill": "escalation-ladder",
    "name": "Escalation Ladder",
    "school": "Debugging",
    "schoolName": "School of Remediation",
    "status": "—",
    "effect": "Structured protocol for when an agent is stuck — escalating from self-recovery to user collaboration to full retreat. Fills the gap between trajectory-guard (detects stuck) and summarize (bails out)."
  },
  {
    "skill": "iterative-patch-repair",
    "name": "Iterative Patch Repair",
    "school": "Debugging",
    "schoolName": "School of Remediation",
    "status": "—",
    "effect": "Loop of generate patch → run test → capture runtime state → refine patch. Max N iterations with patch augmentation to avoid overfitting. Use when first patch attempt failed, bug has multiple plausible fixes, or test feedback reveals the fix was close but not quite right."
  },
  {
    "skill": "log-trace-correlation",
    "name": "Log Trace Correlation",
    "school": "Debugging",
    "schoolName": "School of Remediation",
    "status": "—",
    "effect": "Correlate error logs and stack traces to source code — map each frame to a file:line, identify root cause, and produce a minimal fix. Use when you have an error log with a stack trace and need to determine which file, function, and line caused the failure without guesswork."
  },
  {
    "skill": "minimal-reproduction",
    "name": "Minimal Reproduction",
    "school": "Debugging",
    "schoolName": "School of Remediation",
    "status": "—",
    "effect": "Write the smallest possible test that demonstrates the bug, then use it as ammunition for debugging."
  },
  {
    "skill": "network-api-debugging",
    "name": "Network / API Debugging",
    "school": "Debugging",
    "schoolName": "School of Remediation",
    "status": "—",
    "effect": "Diagnose and fix network and API failures — CORS, auth token issues, rate limiting, redirect chains, WebSocket drops, and HTTP request/response mismatches."
  },
  {
    "skill": "purify-test-output",
    "name": "Or from file: python purify_test_output.py --file /tmp/raw_output.txt",
    "school": "Debugging",
    "schoolName": "School of Remediation",
    "status": "—",
    "effect": "Use when failing test output contains >50% framework noise (site-packages, node_modules) that drowns out user code, or when multiple tests fail and you need to isolate the most relevant failure first."
  },
  {
    "skill": "root-cause-analysis",
    "name": "Root Cause Analysis for AI Agents",
    "school": "Debugging",
    "schoolName": "School of Remediation",
    "status": "—",
    "effect": "Distinguish symptoms from causes, verify causal chains, fix the underlying defect. Stops recurring regressions caused by workaround hacks. Use when a bug returns after being 'fixed', multiple symptoms share a cause, or a fix in one area breaks another."
  },
  {
    "skill": "specter",
    "name": "Specter",
    "school": "Debugging",
    "schoolName": "School of Remediation",
    "status": "—",
    "effect": "Abduce the bug — generate competing hypotheses, locate code by structural relationship, then disconfirm until one survivor remains. Use when the crash site is not the cause, the bug is 'weird,' or your first instinct is suspect."
  },
  {
    "skill": "time-traveling-debugger",
    "name": "Time-Traveling Debugger",
    "school": "Debugging",
    "schoolName": "School of Remediation",
    "status": "—",
    "effect": "When a bug occurs, record a deterministic execution trace forward, then replay it in reverse from the crash point to find the exact line where state first diverged. Spawns 'past self' and 'future self' that meet at the divergence."
  },
  {
    "skill": "effective-web-search",
    "name": "Effective Web Search",
    "school": "Research",
    "schoolName": "School of Research",
    "status": "—",
    "effect": "Web search discipline for technical research. Official-docs-first, version-aware, full GitHub issue follow-through."
  },
  {
    "skill": "add-new-skill-to-repository",
    "name": "Add New Skill to GrimoireStack Repository",
    "school": "Development & Tooling",
    "schoolName": "School of Tools",
    "status": "—",
    "effect": "Standardized process for adding a new skill to the GrimoireStack repository with proper documentation, installation support, and cross-platform verification."
  },
  {
    "skill": "bulk-rename-and-update-references",
    "name": "Bulk Rename Files and Update Cross-References",
    "school": "Development & Tooling",
    "schoolName": "School of Tools",
    "status": "—",
    "effect": "Use when renaming many files where old names appear in content — discover references first to avoid broken links and stale cross-references."
  },
  {
    "skill": "skill-development-with-supporting-files",
    "name": "Developing Skills with Supporting Files",
    "school": "Development & Tooling",
    "schoolName": "School of Tools",
    "status": "—",
    "effect": "Use when a skill depends on scripts, templates, or other supporting files — package them so installation copies the full set, not just SKILL.md."
  },
  {
    "skill": "project-folder-architecture",
    "name": "Project Folder Architecture",
    "school": "Development & Tooling",
    "schoolName": "School of Tools",
    "status": "—",
    "effect": ">"
  },
  {
    "skill": "unit-test-debugging",
    "name": "Unit Test Debugging",
    "school": "Development & Tooling",
    "schoolName": "School of Tools",
    "status": "—",
    "effect": "Systematic workflow for fixing failing unit tests by first determining whether the tests or the code under test are the source of truth. Use when fixing test failures, debugging test suites, resolving \"tests are passing/failing unexpectedly,\" or when an agent keeps changing code to match failing tests without investigating root cause. Also use when improving weak passing tests that do not actually prove correctness."
  }
];
