/**
 * emit-schools.mjs — Build the schools[] array from skill records.
 *
 * Inputs: an array of parsed skills (each with skill id, topic,
 * display name, effect, status, note, combos) plus the curated
 * overlay (hand-maintained themed names, statuses, notes, combos).
 *
 * Returns: a JSON-serializable schools array sorted by school name,
 * with spells sorted alphabetically by name within each school.
 *
 * Pure function — no file I/O. The caller writes the result.
 */

import { TOPIC_META } from './topic-meta.mjs';

/**
 * @param {Array<{skill, topic, name, effect, status, note, combos}>} skills
 * @param {{spells: object, schools: object}} overlay
 * @returns {Array}
 */
export function buildSchools(skills, overlay) {
  const byTopic = groupBy(skills, s => s.topic);

  const schools = [];
  for (const [topic, topicSkills] of byTopic) {
    const theme = overlay.schools[topic] || TOPIC_META[topic] || deriveTopicMeta(topic);
    topicSkills.sort((a, b) => a.name.localeCompare(b.name));
    schools.push({
      id: theme.id,
      real: theme.real,
      name: theme.name,
      desc: theme.desc,
      spells: topicSkills.map(toSpell),
    });
  }
  schools.sort((a, b) => a.name.localeCompare(b.name));
  return schools;
}

function toSpell(s) {
  const spell = { name: s.name, skill: s.skill, effect: s.effect, status: s.status };
  if (s.note) spell.note = s.note;
  if (s.combos) spell.combos = s.combos;
  return spell;
}

function deriveTopicMeta(topic) {
  const titleCased = topic
    .split('-')
    .map(w => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');
  return {
    id: topic,
    real: titleCased,
    name: `School of ${titleCased}`,
    desc: `Skills related to ${topic.replace(/-/g, ' ')}.`,
  };
}

function groupBy(arr, keyFn) {
  const map = new Map();
  for (const item of arr) {
    const key = keyFn(item);
    if (!map.has(key)) map.set(key, []);
    map.get(key).push(item);
  }
  return map;
}

export function renderSchoolsSource(schools) {
  return `// AUTO-GENERATED by scripts/registry/index.mjs — DO NOT EDIT
// To change a spell, edit the SKILL.md frontmatter in its source directory.

const schools = ${JSON.stringify(schools, null, 2)};

export default schools;
`;
}
