// AUTO-GENERATED by scripts/registry/index.mjs — DO NOT EDIT
// To change a spell, edit the SKILL.md frontmatter in its source directory.

const schools: Array<{
  id: string;
  real: string;
  name: string;
  desc: string;
  spells: Array<{
    name: string;
    skill: string;
    effect: string;
    status: string;
    note?: string;
    combos?: string[];
  }>;
}> = [
  {
    "id": "systems-and-architecture",
    "real": "Systems & Architecture",
    "name": "School of Architecture",
    "desc": "Design rituals for systems that endure across dimensions of scale, time, and team boundaries.",
    "spells": [
      {
        "name": "Architecture Evolution Review",
        "skill": "architecture-evolution-review",
        "effect": "Review the repository as a living system. Detect architectural drift, feature erosion, and long-term maintenance risks.",
        "status": "—"
      },
      {
        "name": "Architecture Maintenance",
        "skill": "maintain-architecture",
        "effect": "Review completed work for architectural quality: feature ownership, dependency direction, module quality, and long-term scalability.",
        "status": "—"
      },
      {
        "name": "Cross-Domain Analogy",
        "skill": "cross-domain-analogy-generator",
        "effect": "Generate cross-domain analogies — break fixation by mapping problem structures to foreign fields (biology, music, traffic) and transferring insights.",
        "status": "—"
      },
      {
        "name": "Designing Data-Intensive Applications for AI Agents",
        "skill": "designing-data-intensive-applications-ai",
        "effect": "Reason about data systems: storage choices, replication, consistency, partitioning, queues, failure modes, and operational tradeoffs.",
        "status": "—"
      },
      {
        "name": "Domain-Driven Design for AI Agents",
        "skill": "domain-driven-design",
        "effect": "Bounded contexts, ubiquitous language, aggregates, context maps, domain events, anti-corruption layers.",
        "status": "—"
      },
      {
        "name": "Everything-as-Code Conceptualizer",
        "skill": "everything-as-code-conceptualizer",
        "effect": "Codify messy human problems as pseudocode to reveal hidden assumptions, missing decisions, and edge cases.",
        "status": "—"
      },
      {
        "name": "Feature Architecture Planning",
        "skill": "plan-feature-architecture",
        "effect": "Decide ownership, placement, module boundaries, dependencies, and project impact before writing code.",
        "status": "—"
      },
      {
        "name": "Improve Codebase Architecture",
        "skill": "improve-codebase-architecture",
        "effect": "Find deepening opportunities informed by the domain language in CONTEXT.md and decisions in docs/adr/.",
        "status": "—"
      },
      {
        "name": "Release It! Stability Patterns for AI Agents",
        "skill": "release-it-stability",
        "effect": "Circuit breakers, bulkheads, timeouts, load shedding, steady-state hygiene for production failure modes.",
        "status": "—"
      },
      {
        "name": "Security Review Protocol",
        "skill": "security-review-protocol",
        "effect": "4-phase security review fusing STRIDE, hazard analysis, LLM vuln audit, and expanded threat-modeling guidance (assets, boundaries, secrets, input validation, authz, failure modes, attacker perspective).",
        "status": "—"
      },
      {
        "name": "SRE / Error Budget Thinking for AI Agents",
        "skill": "sre-error-budget",
        "effect": "SLOs, error budgets, toil budgets, and change-velocity governance. Spend the budget on speed when healthy; freeze changes when depleted.",
        "status": "—"
      },
      {
        "name": "System Architecture Audit for AI Agents",
        "skill": "system-architecture-audit",
        "effect": "4-phase audit fusing Thinking in Systems, DDD, DDIA, and Release It. Reveals structural problems before they cascade.",
        "status": "—"
      },
      {
        "name": "Team Topologies for Multi-Agent Systems",
        "skill": "team-topologies-ai",
        "effect": "Stream-aligned, platform, enabling, and complicated-subsystem boundaries with explicit interaction modes.",
        "status": "—"
      },
      {
        "name": "The Goal — Theory of Constraints for Engineering Agents",
        "skill": "the-goal-theory-of-constraints-ai",
        "effect": "Find the one constraint, ignore non-constraints, exploit then elevate it, repeat when it moves.",
        "status": "—"
      },
      {
        "name": "Thinking in Systems — State Machine Protocol for AI Agents",
        "skill": "thinking-in-systems-state-machine",
        "effect": "Model stocks, flows, delays, leverage points, and blast radius before touching the system.",
        "status": "—"
      },
      {
        "name": "Vibe Coding Security Hardening",
        "skill": "vibe-coding-security-hardening",
        "effect": "Hardening checklist for vulnerabilities LLMs reliably introduce: exposed secrets, missing RLS, broken auth, injection flaws, insecure defaults.",
        "status": "—"
      }
    ]
  },
  {
    "id": "reasoning",
    "real": "Reasoning & Faithfulness",
    "name": "School of Cognition",
    "desc": "Mental models and structured thought for when the problem itself is unclear or risks hallucination.",
    "spells": [
      {
        "name": "Claim Verification Reasoning",
        "skill": "claim-verification-reasoning",
        "effect": "Atomic decomposition with confidence labels and tool-grounded verification.",
        "status": "—"
      },
      {
        "name": "CoT Pruning Reasoning",
        "skill": "cot-pruning-reasoning",
        "effect": "Two-pass prune retains only the steps that move the answer (coarse step-level, then fine token-level).",
        "status": "—"
      },
      {
        "name": "Faithfulness-Aware Reasoning",
        "skill": "faithfulness-aware-reasoning",
        "effect": "Detect and prevent faithfulness hallucinations where claims aren't logically entailed by the premises.",
        "status": "—"
      },
      {
        "name": "Prism",
        "skill": "prism",
        "effect": "Force numeric confidence on each claim, compress to its essence, then verify the compression reconstructs the original.",
        "status": "—"
      },
      {
        "name": "Reasoning Integrity Chain for AI Agents",
        "skill": "reasoning-integrity-chain",
        "effect": "Escalating 4-phase verification chain: faithfulness, claims, contradiction, selective halt.",
        "status": "—"
      },
      {
        "name": "Selective Halt Reasoning",
        "skill": "selective-halt-reasoning",
        "effect": "Monitor for semantic stabilization and halt early when consecutive steps converge on equivalent conclusions.",
        "status": "—"
      },
      {
        "name": "Self-Contradiction Trap",
        "skill": "self-contradiction-trap",
        "effect": "Maintain a belief store of claims made during a session. Detect contradictions and force resolution before continuing.",
        "status": "—"
      }
    ]
  },
  {
    "id": "mcp-servers",
    "real": "MCP Servers",
    "name": "School of Conduits",
    "desc": "Model Context Protocol servers that extend agent capabilities with structured tools.",
    "spells": [
      {
        "name": "Active Inference Agent",
        "skill": "active-inference-agent",
        "effect": "MCP server implementing a practical Active Inference agent based on Friston's Free Energy Principle.",
        "status": "—"
      },
      {
        "name": "Evolutionary Tool Composer",
        "skill": "evolutionary-tool-composer",
        "effect": "MCP server that runs an evolutionary algorithm to discover and optimize agent tool chains, prompt strategies, and code solutions.",
        "status": "—"
      }
    ]
  },
  {
    "id": "orchestration",
    "real": "Agent Orchestration",
    "name": "School of Confluence",
    "desc": "Incantations for orchestrating multiple agents, sharing reasoning memory, and coordinating parallel workstreams.",
    "spells": [
      {
        "name": "Agentic Patterns Orchestrator — State Machine Protocol",
        "skill": "agentic-design-patterns-orchestrator-state-machine",
        "effect": "Enforce a phased workflow with explicit gates between classify, plan, execute, reflect, and verify.",
        "status": "—"
      },
      {
        "name": "Monte Carlo Tree Search for Agents",
        "skill": "monte-carlo-tree-search",
        "effect": "Allocate search effort to branches that earn it through probes and scoring.",
        "status": "—"
      },
      {
        "name": "Navigator",
        "skill": "navigator",
        "effect": "Scout reads code, Thought-Retriever stores the reasoning trail so future sessions resume from where you stopped.",
        "status": "—"
      },
      {
        "name": "Octopus",
        "skill": "octopus",
        "effect": "Coordinate parallel sub-agents with bounded concurrency — define shared contracts, delegate with auto-healing arms, retract on failure. Use when 3+ workstreams share a contract and parallel speedup beats coordination overhead.",
        "status": "—"
      },
      {
        "name": "Pre-Flight Intent Verification",
        "skill": "pre-flight-intent-verification",
        "effect": "Surface the critical assumption, crystallize intent into testable spec, ground facts before acting.",
        "status": "—"
      },
      {
        "name": "Rashomon-Triad Hybrid",
        "skill": "rashomon-triad-hybrid",
        "effect": "Parallel perspectives with conflicting goals run independent abductive-deductive-inductive cycles, then argue via attack graph.",
        "status": "—"
      },
      {
        "name": "Scout",
        "skill": "scout",
        "effect": "Scout context — a fast sub-agent reads files and returns only distilled relevant context, saving tokens and reducing distraction for the main model. Use when the codebase is large, you need scoped findings rather than raw file dumps, or the main task needs file context you don't already have.",
        "status": "—"
      },
      {
        "name": "Separation of Concerns for AI Agent Orchestration",
        "skill": "separation-of-concerns",
        "effect": "Keep planning, diagnosis, observation, and execution phases intellectually isolated.",
        "status": "—"
      },
      {
        "name": "SOP Evolution Memory",
        "skill": "sop-evolution-memory",
        "effect": "Distill trajectories into reusable Standard Operating Procedures (SOPs) after repeated successes on a class of tasks.",
        "status": "—"
      },
      {
        "name": "Sub-Agent Composer",
        "skill": "subagent-composer",
        "effect": "Compose high-context sub-agent briefs that eliminate first-pass failures.",
        "status": "—"
      },
      {
        "name": "Sub-Agent Laws",
        "skill": "subagent-laws",
        "effect": "Standing behavioral constraints every sub-agent must follow. Enforce scope discipline, test integrity, and communication standards.",
        "status": "—"
      },
      {
        "name": "Weak-Link Detection for Multi-Agent Systems",
        "skill": "weak-link-detection-multi-agent",
        "effect": "Identify and isolate the weakest reasoning chain in multi-agent outputs before aggregation.",
        "status": "—"
      }
    ]
  },
  {
    "id": "software-development",
    "real": "Software Development",
    "name": "School of Crafting",
    "desc": "Practical incantations for building, renaming, searching through, and shipping code.",
    "spells": [
      {
        "name": "1. Run existing tests",
        "skill": "llm-pre-push-review",
        "effect": "Checklist and protocol for catching systematic LLM coding failures: overcorrection, hallucinated logic, silent vulnerabilities, missing edge cases.",
        "status": "—"
      },
      {
        "name": "1. Tests",
        "skill": "pre-deployment-gate",
        "effect": "Complete pre-deployment checklist merging LLM Pre-Push Review with Vibe Coding Security Hardening.",
        "status": "—"
      },
      {
        "name": "API Design and Backward Compatibility",
        "skill": "api-design-backward-compatibility",
        "effect": "Contract-first design and additive-only change discipline for evolving APIs without breaking clients.",
        "status": "—"
      },
      {
        "name": "API Surface Anchoring",
        "skill": "api-surface-anchoring",
        "effect": "Verify every external API call against current docs to prevent hallucinated APIs.",
        "status": "—"
      },
      {
        "name": "Code Knowledge Graph MCP",
        "skill": "code-knowledge-graph-mcp",
        "effect": "MCP server with structured symbol and call-graph queries. Navigate code by structure, not by string search.",
        "status": "—"
      },
      {
        "name": "Code Review Excellence",
        "skill": "code-review-excellence",
        "effect": "Provide constructive feedback, catch bugs early, and foster knowledge sharing while maintaining team morale.",
        "status": "—"
      },
      {
        "name": "Codebase Divide-and-Conquer Search",
        "skill": "codebase-divide-conquer-search",
        "effect": "Divide a large codebase into summary-ranked zones and conquer each with a parallel sub-agent. Find code by behavior, not by name.",
        "status": "—"
      },
      {
        "name": "Coordinated Change",
        "skill": "coordinated-change",
        "effect": "Ensure consistency when a fix or feature requires touching 2+ files that must stay consistent.",
        "status": "—"
      },
      {
        "name": "Critical System Interrogation",
        "skill": "critical-system-interrogation",
        "effect": "Stress-test critical system paths (auth pipelines, payment flows, data validation) for correctness, race conditions, security flaws, and architectural integrity.",
        "status": "—"
      },
      {
        "name": "Dev Diagnostics MCP",
        "skill": "dev-diagnostics-mcp",
        "effect": "Run diagnostics across multiple tools (eslint, tsc, vitest, pytest, biome, ruff) and compare before/after for contamination.",
        "status": "—"
      },
      {
        "name": "ESLint",
        "skill": "lint-battalion",
        "effect": "Batch-process 50+ linter errors as a bulk remediation problem, not 50 separate decisions.",
        "status": "—"
      },
      {
        "name": "Git Surgery",
        "skill": "git-surgery",
        "effect": "Recover from local git disasters: detached HEAD, botched rebase, accidental commits, merge conflicts.",
        "status": "—"
      },
      {
        "name": "Native Data Fetching",
        "skill": "native-data-fetching",
        "effect": "Covers fetch API, React Query, SWR, error handling, caching, offline support, and Expo Router data loaders.",
        "status": "—"
      },
      {
        "name": "Recency Grounding",
        "skill": "recency-grounding",
        "effect": "User-invoked pre-claim audit for one unfamiliar or post-cutoff library. Invoke with `/recency-grounding <library> [version]`.",
        "status": "—"
      },
      {
        "name": "Review Changes",
        "skill": "review-changes",
        "effect": "Structured review checklist for evaluating code changes systematically.",
        "status": "—"
      },
      {
        "name": "Review Ladder Plus",
        "skill": "review-ladder-plus",
        "effect": "Multi-agent code review ladder for production-grade QA: security, auth, data, concurrency.",
        "status": "—"
      },
      {
        "name": "Safe Refactor",
        "skill": "refactor-safely",
        "effect": "Characterization testing to capture existing behavior, then bounded changes with immediate verification.",
        "status": "—"
      },
      {
        "name": "Super Review TypeScript",
        "skill": "super-review-typescript",
        "effect": "Targets the five LLM-specific failure modes: security vulnerabilities, hallucinated APIs, logic errors, type-safety violations, architectural decay.",
        "status": "—"
      },
      {
        "name": "Verified API Workflow",
        "skill": "verified-api-workflow",
        "effect": "Every external API call must be traceable to a doc you actually checked.",
        "status": "—"
      },
      {
        "name": "Verified Code Synthesizer",
        "skill": "verified-synthesize",
        "effect": "Verify code correctness through formal Dafny specifications — given a natural language spec, produce provably correct code with pre/postconditions and loop invariants. Use for critical bugs in security, memory safety, or financial calculations; pre-refactor spec locking; or API contracts across module boundaries.",
        "status": "—"
      },
      {
        "name": "Verify Before Integrate",
        "skill": "verify-before-integrate",
        "effect": "Verify the actual system behavior rather than matching abstract terminology when integrating research or external docs.",
        "status": "—"
      }
    ]
  },
  {
    "id": "execution",
    "real": "Execution & Improvement",
    "name": "School of Execution",
    "desc": "Rituals for solving problems, executing plans, and improving systems over time.",
    "spells": [
      {
        "name": "Blueprint",
        "skill": "blueprint",
        "effect": "Blueprint a messy problem into formal schema — types, operations, events, constraints — so contradictions, gaps, and hidden assumptions surface as bugs. Use when scope keeps expanding, stakeholders talk past each other, or informal requirements need precision.",
        "status": "—"
      },
      {
        "name": "Checklist Manifesto — State Machine Protocol for AI Agents",
        "skill": "checklist-manifesto",
        "effect": "Build the smallest useful checklist for high-stakes procedures, gate execution on checklist completion, stop cleanly and escalate if it cannot be cleared.",
        "status": "—"
      },
      {
        "name": "Estimate token cost of files",
        "skill": "context-budget-operator",
        "effect": "Track token budget, classify information needs, compress aggressively, and decide breadth-vs-depth based on remaining runway.",
        "status": "—"
      },
      {
        "name": "How to Solve It — State Machine Protocol for AI Agents",
        "skill": "how-to-solve-it-state-machine",
        "effect": "Frame the problem, gather evidence, explore via hypothesis, plan, reflect. Designed to prevent premature coding.",
        "status": "—"
      },
      {
        "name": "Intent Specification Protocol",
        "skill": "intent-specification-protocol",
        "effect": "Crystallize vague coding requests into precise, testable specifications before writing any code. Prevents the Intent-Behavior Mirroring Effect.",
        "status": "—"
      },
      {
        "name": "Iterative Spec Authoring",
        "skill": "iterative-spec-authoring",
        "effect": "Author a detailed technical spec grounded in research, refine through up to 3 judge-LLM review cycles, then present to the user for final approval.",
        "status": "—"
      },
      {
        "name": "Legacy Rescue Protocol",
        "skill": "legacy-rescue-protocol",
        "effect": "Fuse of Working Effectively with Legacy Code + Refactoring State Machine. Characterize legacy behavior, create seams, then transform in bounded slices with anti-loop protection.",
        "status": "—"
      },
      {
        "name": "OODA Loop — Rapid Response Protocol",
        "skill": "ooda-loop-state-machine",
        "effect": "Observe, Orient, Decide, Act, Loop. Maintains decision tempo against an environment that shifts between every move.",
        "status": "—"
      },
      {
        "name": "PDCA / Shewhart Cycle",
        "skill": "pdca-deming",
        "effect": "Improve a process through a measurement-anchored cycle: plan with a measurable prediction, do, check actual vs predicted, then standardize or escalate. Standardize only what the check confirmed.",
        "status": "—"
      },
      {
        "name": "Retrospective",
        "skill": "retrospective",
        "effect": "After an incident, shipped feature, or completed project, systematically learn from what happened.",
        "status": "—"
      },
      {
        "name": "Speculative Drafting with Verification",
        "skill": "speculative-drafting-verification",
        "effect": "Generate multiple solution branches in parallel, verify each against hard constraints, select the best.",
        "status": "—"
      },
      {
        "name": "Split Large Files — Boundary-Driven Extraction Protocol",
        "skill": "split-large-files",
        "effect": "Split large files along change boundaries, not line counts. Investigate before extracting, require strong architectural signals.",
        "status": "—"
      },
      {
        "name": "Step-Level Verification Protocol",
        "skill": "step-level-verification-protocol",
        "effect": "Verify each step before proceeding so a wrong step doesn't cascade into a chain of unjustified conclusions.",
        "status": "—"
      },
      {
        "name": "Structured Feature Planning",
        "skill": "structured-feature-planning",
        "effect": "Read files, search for patterns, self-review twice, then execute. Never hallucinate when confused.",
        "status": "—"
      },
      {
        "name": "Summarize — Emergency Stop + Handoff Report",
        "skill": "summarize",
        "effect": "Emergency stop + perfect handoff report so the next agent loses nothing.",
        "status": "—"
      },
      {
        "name": "The Pragmatic Programmer — State Machine Protocol for AI Agents",
        "skill": "pragmatic-programmer-state-machine",
        "effect": "Bounded changes, reversible choices, automation over repeated toil, root-cause fixes over symptom patches.",
        "status": "—"
      },
      {
        "name": "Toyota Kata",
        "skill": "toyota-kata-state-machine",
        "effect": "Frame target, analyze current, attack one obstacle at a time, run a PDCA experiment, learn, repeat.",
        "status": "—"
      },
      {
        "name": "Trajectory Guard — Detect and Recover from Failure Spirals",
        "skill": "trajectory-guard",
        "effect": "Detect agent failure spirals — repetitive loops, specification drift, and stuck trajectories — and forcibly redirect strategy.",
        "status": "—"
      },
      {
        "name": "Verify a batch of assumptions from a file",
        "skill": "assumption-grounding",
        "effect": "State every assumption explicitly, verify with the cheapest possible check, and only proceed on confirmation.",
        "status": "—"
      },
      {
        "name": "Zero-Defect Protocol",
        "skill": "zero-defect-protocol",
        "effect": "Mission-critical feature protocol: data contracting, red-team critique, pre-mortem, 3x critique loop, and speculative prototyping before any code is written.",
        "status": "—"
      }
    ]
  },
  {
    "id": "judgment-and-routing",
    "real": "Judgment & Decision-Making",
    "name": "School of Judgment",
    "desc": "Incantations for routing decisions, weighing tradeoffs, and routing problems to the right approach.",
    "spells": [
      {
        "name": "Advocatus Diaboli",
        "skill": "advocatus-diaboli",
        "effect": "Stress-test a proposal against a separate adversarial sub-agent to break anchoring.",
        "status": "—"
      },
      {
        "name": "Bayesian Belief Updating",
        "skill": "bayesian-updating",
        "effect": "Maintain explicit priors updated by likelihood, avoiding over- and under-reaction to new evidence.",
        "status": "—"
      },
      {
        "name": "Cognitive Bias Checklist for AI Agents",
        "skill": "cognitive-bias-checklist",
        "effect": "Explicit checklist to catch bias contamination before finalizing slow-mode recommendations.",
        "status": "—"
      },
      {
        "name": "Counterfactual Policy Testing",
        "skill": "counterfactual-policy-testing",
        "effect": "Compare a decision against null, opposite, and partial counterfactuals before committing.",
        "status": "—"
      },
      {
        "name": "Explore vs Exploit",
        "skill": "explore-vs-exploit-state-machine",
        "effect": "Explicit explore/exploit protocol: frame the decision, budget the search, explore with purpose, stop deliberately, act when search stops earning its keep.",
        "status": "—"
      },
      {
        "name": "Failure Analysis Protocol",
        "skill": "failure-analysis-protocol",
        "effect": "Three failure lenses merged: invert success, narrate specific failures, trace cascading consequences.",
        "status": "—"
      },
      {
        "name": "Failure Swarm",
        "skill": "failure-swarm",
        "effect": "Swarm 3-5 critic personas over a spec to surface failure modes pre-implementation. User-invoked; type `/failure-swarm`.",
        "status": "—"
      },
      {
        "name": "First Principles Thinking for AI Agents",
        "skill": "first-principles",
        "effect": "Decompose to axiomatic foundations and reason upward from what must be true.",
        "status": "—"
      },
      {
        "name": "Future Mortem",
        "skill": "future-mortem",
        "effect": "After code is written, assume it will cause future pain and work backward to find what will bite: debt with interest, extension traps, hidden assumptions, maintenance memory, time bombs, and upgrade cliffs. Use when implementation is done and the agent must surface what the code will cost the project later.",
        "status": "—"
      },
      {
        "name": "Inversion",
        "skill": "inversion-mental-model-state-machine",
        "effect": "Enforce failure-mode mapping and guardrail derivation before recommending success paths.",
        "status": "—"
      },
      {
        "name": "Metacognitive Monitoring",
        "skill": "metacognitive-monitoring",
        "effect": "Explicit KEEP/WITHDRAW decisions tied to measured withdrawal delta — know when you don't know.",
        "status": "—"
      },
      {
        "name": "Occam's Razor for AI Agents",
        "skill": "occams-razor",
        "effect": "Favor the simplest sufficient explanation or solution. Try the simplest thing that fits the evidence before escalating.",
        "status": "—"
      },
      {
        "name": "Pre-Mortem",
        "skill": "pre-mortem-state-machine",
        "effect": "Validate a plan before execution: assume failure has already happened, generate specific failure narratives, rank them, and adjust the plan.",
        "status": "—"
      },
      {
        "name": "Problem-Mode Router (Cynefin)",
        "skill": "problem-mode-router-cynefin-state-machine",
        "effect": "Enforce Cynefin domain classification as a hard gate before any tool use or execution.",
        "status": "—"
      },
      {
        "name": "Recognition-Primed Triage",
        "skill": "recognition-primed-triage-state-machine",
        "effect": "Gated incident-response protocol: recognize the pattern, simulate the first action, act within scope, reassess, hand off.",
        "status": "—"
      },
      {
        "name": "Reference Class Forecasting for AI Agents",
        "skill": "reference-class-forecasting",
        "effect": "Anchor to similar past projects before reasoning from the specifics.",
        "status": "—"
      },
      {
        "name": "Second-Order Thinking for AI Agents",
        "skill": "second-order-thinking",
        "effect": "Chain consequences past first-order until the system-level outcome is clear.",
        "status": "—"
      },
      {
        "name": "Six Thinking Hats",
        "skill": "six-thinking-hats",
        "effect": "Separate fact, intuition, caution, optimism, creativity, and process into six discrete rounds.",
        "status": "—"
      },
      {
        "name": "Steelmanning for AI Agents",
        "skill": "steelmanning",
        "effect": "Construct the strongest opposing case before committing to a recommendation.",
        "status": "—"
      },
      {
        "name": "Thinking Fast and Slow for Software Agents",
        "skill": "kahneman-thinking-fast-slow-software-agent",
        "effect": "Switch between fast pattern recognition and slow deliberation as stakes demand.",
        "status": "—"
      },
      {
        "name": "Thoroughness Check (ETTO)",
        "skill": "thoroughness-check-etto-state-machine",
        "effect": "Gate task execution by the Efficiency-Thoroughness Trade-Off: classify rigor 1-5, meet the evidence bar, act within the mode, validate to match.",
        "status": "—"
      },
      {
        "name": "Unsafe Control Actions / Hazard Analysis",
        "skill": "unsafe-control-actions-hazard-analysis",
        "effect": "Analyze how a control action could become unsafe before recommending or performing it.",
        "status": "—"
      }
    ]
  },
  {
    "id": "testing",
    "real": "Testing & Measurement",
    "name": "School of Measurement",
    "desc": "Empirical measurement of skill effectiveness and code quality.",
    "spells": [
      {
        "name": "E2E Cross-Check Protocol",
        "skill": "e2e-crosscheck",
        "effect": "Bidirectional audit between E2E test selectors/assertions and source code. Reconciles every test identifier, text assertion, and navigation route.",
        "status": "—"
      },
      {
        "name": "E2E Testing Philosophy & Architecture — Reference",
        "skill": "e2e-testing-philosophy-and-architecture",
        "effect": "Reference for E2E testing mindset, architecture, and strategy: testing epistemology, 3-layer BDR architecture, risk-based prioritization, data realism principles.",
        "status": "—"
      },
      {
        "name": "Good: per-run copied snapshot",
        "skill": "skill-ab-evaluation",
        "effect": "A/B evaluate any GrimoireStack skill against a baseline using isolated subagents, 5 trials each, and an objective rubric.",
        "status": "—"
      },
      {
        "name": "Mobile E2E Testing: The Hunter's Mindset",
        "skill": "mobile-e2e-testing-enterprise-guide",
        "effect": "Hunter's mindset for mobile E2E testing: what to test, how to catch real bugs, and avoid traps.",
        "status": "—"
      },
      {
        "name": "Premortem: E2E Test Audit Protocol",
        "skill": "e2e-test-premortem",
        "effect": "Premortem for E2E test changes. Audit coverage gaps, data realism, failure-mode coverage, and assertion quality.",
        "status": "—"
      },
      {
        "name": "Test-Driven Development",
        "skill": "test-driven-development",
        "effect": "Red-green-refactor loop. Write the test first, watch it fail, write the minimal fix, then refactor.",
        "status": "—"
      }
    ]
  },
  {
    "id": "mlops",
    "real": "Mlops",
    "name": "School of Mlops",
    "desc": "Skills related to mlops.",
    "spells": [
      {
        "name": "Local LLM Tooling Skill",
        "skill": "local-llm-tooling",
        "effect": "Run, prompt, and extract structured output from local LLMs (e.g., Ollama, llama.cpp).",
        "status": "—"
      }
    ]
  },
  {
    "id": "output-quality",
    "real": "Output Quality",
    "name": "School of Refinement",
    "desc": "Incantations for improving, verifying, and stress-testing output before it ships.",
    "spells": [
      {
        "name": "Bounded Self-Revision",
        "skill": "bounded-self-revision",
        "effect": "Capped self-critique passes that terminate on improvement or budget exhaustion.",
        "status": "—"
      },
      {
        "name": "Cognitive Load Operator — State Machine Protocol",
        "skill": "cognitive-load-operator-state-machine",
        "effect": "Inspect complexity and replace high-load structures with lower-load equivalents.",
        "status": "—"
      },
      {
        "name": "Documentation Craft",
        "skill": "documentation-craft",
        "effect": "Multi-phase pipeline from outline to verified explanation, audience-driven and source-grounded.",
        "status": "—"
      },
      {
        "name": "Feynman Technique for AI Agents",
        "skill": "feynman-technique",
        "effect": "Explain from scratch in plain language and identify where the explanation breaks.",
        "status": "—"
      },
      {
        "name": "MECE / Pyramid Principle for AI Agents",
        "skill": "mece-pyramid-principle",
        "effect": "Enforce mutually exclusive, collectively exhaustive categories under a single governing thought.",
        "status": "—"
      },
      {
        "name": "Self Verify Pipeline",
        "skill": "self-verify-pipeline",
        "effect": "Escalating verification chain of bounded revision, claim decomposition, and tool-grounded critique.",
        "status": "—"
      },
      {
        "name": "Self-Consistency Check for AI Agents",
        "skill": "self-consistency",
        "effect": "Generate independent reasoning paths and check whether they converge.",
        "status": "—"
      },
      {
        "name": "Tool-Interactive Critic",
        "skill": "tool-interactive-critic",
        "effect": "External tools critique the output before it is trusted.",
        "status": "—"
      },
      {
        "name": "Tree of Thoughts for AI Agents",
        "skill": "tree-of-thoughts",
        "effect": "Branch, evaluate, and prune candidate solutions before committing.",
        "status": "—"
      }
    ]
  },
  {
    "id": "debugging",
    "real": "Debugging",
    "name": "School of Remediation",
    "desc": "Incantations to banish bugs and restore order to broken code.",
    "spells": [
      {
        "name": "Before (buggy)",
        "skill": "simulate-instrumentation",
        "effect": "Auto-insert temporary print/logging statements at key points in the code, run the failing test, and feed the captured runtime state to the LLM.",
        "status": "—"
      },
      {
        "name": "Bisect Debugging",
        "skill": "bisect-debugging",
        "effect": "Isolate the exact commit that introduced a bug using binary search through git history.",
        "status": "—"
      },
      {
        "name": "Bug Inquisition",
        "skill": "bug-inquisition",
        "effect": "Deep root-cause debugging with mandatory context-gathering. Fuses root-cause analysis, specter, diagnose, debug-to-fix-pipeline, occam-root-cause, and reasoning-integrity-chain into one sequential protocol.",
        "status": "—"
      },
      {
        "name": "Debug Issue",
        "skill": "debug-issue",
        "effect": "Force the reproduce → isolate → fix → verify cycle. Graph-powered code navigation traces issues through the system along dataflow edges. Use when the bug spans multiple modules or services, the crash site isn't the cause, or state diverges across an async boundary.",
        "status": "—"
      },
      {
        "name": "Debug Subagent",
        "skill": "debug-subagent",
        "effect": "Gate debugging behind a dedicated subagent — consult it before any code edit. Wraps debugger complexity behind natural-language queries. Use when the fix is not immediately obvious from the error, for multi-file bugs needing runtime state inspection, or when static analysis hasn't revealed the root cause.",
        "status": "—"
      },
      {
        "name": "Debug-to-Fix Pipeline for AI Agents",
        "skill": "debug-to-fix-pipeline",
        "effect": "6-phase pipeline that increases evidence quality each phase while cutting token waste. Sequences data → hypothesis → isolation → exploitation → repair → verification. Use when debugging is stalling, multi-file bugs need runtime state, or first patch attempt failed.",
        "status": "—"
      },
      {
        "name": "Environment Recovery",
        "skill": "environment-recovery",
        "effect": "Diagnose and fix broken development environments — missing tools, wrong versions, corrupted caches, full disks, permission drift, and dependency hell. The skill every other debugging skill assumes.",
        "status": "—"
      },
      {
        "name": "Escalation Ladder",
        "skill": "escalation-ladder",
        "effect": "Structured protocol for when an agent is stuck — escalating from self-recovery to user collaboration to full retreat. Fills the gap between trajectory-guard (detects stuck) and summarize (bails out).",
        "status": "—"
      },
      {
        "name": "Log Trace Correlation",
        "skill": "log-trace-correlation",
        "effect": "Correlate error logs and stack traces to source code — map each frame to a file:line, identify root cause, and produce a minimal fix. Use when you have an error log with a stack trace and need to determine which file, function, and line caused the failure without guesswork.",
        "status": "—"
      },
      {
        "name": "Minimal Reproduction",
        "skill": "minimal-reproduction",
        "effect": "Write the smallest possible test that demonstrates the bug, then use it as ammunition for debugging.",
        "status": "—"
      },
      {
        "name": "Network / API Debugging",
        "skill": "network-api-debugging",
        "effect": "Diagnose and fix network and API failures — CORS, auth token issues, rate limiting, redirect chains, WebSocket drops, and HTTP request/response mismatches.",
        "status": "—"
      },
      {
        "name": "Or from file: python purify_test_output.py --file /tmp/raw_output.txt",
        "skill": "purify-test-output",
        "effect": "Use when failing test output contains >50% framework noise (site-packages, node_modules) that drowns out user code, or when multiple tests fail and you need to isolate the most relevant failure first.",
        "status": "—"
      },
      {
        "name": "Root Cause Analysis for AI Agents",
        "skill": "root-cause-analysis",
        "effect": "Distinguish symptoms from causes, verify causal chains, fix the underlying defect. Stops recurring regressions caused by workaround hacks. Use when a bug returns after being 'fixed', multiple symptoms share a cause, or a fix in one area breaks another.",
        "status": "—"
      },
      {
        "name": "Specter",
        "skill": "specter",
        "effect": "Abduce the bug — generate competing hypotheses, locate code by structural relationship, then disconfirm until one survivor remains. Use when the crash site is not the cause, the bug is 'weird,' or your first instinct is suspect.",
        "status": "—"
      },
      {
        "name": "Time-Traveling Debugger",
        "skill": "time-traveling-debugger",
        "effect": "When a bug occurs, record a deterministic execution trace forward, then replay it in reverse from the crash point to find the exact line where state first diverged. Spawns 'past self' and 'future self' that meet at the divergence.",
        "status": "—"
      }
    ]
  },
  {
    "id": "research",
    "real": "Research",
    "name": "School of Research",
    "desc": "Skills related to research.",
    "spells": [
      {
        "name": "Effective Web Search",
        "skill": "effective-web-search",
        "effect": "Web search discipline for technical research. Official-docs-first, version-aware, full GitHub issue follow-through.",
        "status": "—"
      }
    ]
  },
  {
    "id": "development",
    "real": "Development & Tooling",
    "name": "School of Tools",
    "desc": "Tooling, utilities, and workflows for development tasks.",
    "spells": [
      {
        "name": "Project Folder Architecture",
        "skill": "project-folder-architecture",
        "effect": "Folder architecture for TypeScript + Expo Router + React Native + Supabase full-stack projects, updated to 2026 conventions. Use when scaffolding a new project, restructuring an existing one, auditing folder health, or answering 'where should this file live?'.",
        "status": "—"
      },
      {
        "name": "Unit Test Debugging",
        "skill": "unit-test-debugging",
        "effect": "Systematic workflow for fixing failing unit tests by first determining whether the tests or the code under test are the source of truth.",
        "status": "—"
      }
    ]
  }
];

export default schools;
