// AUTO-GENERATED by scripts/registry/index.mjs — DO NOT EDIT
// To change a spell, edit the SKILL.md frontmatter in its source directory.

const schools: Array<{
  id: string;
  real: string;
  name: string;
  desc: string;
  spells: Array<{
    name: string;
    skill: string;
    effect: string;
    status: string;
    note?: string;
    combos?: string[];
  }>;
}> = [
  {
    "id": "systems-and-architecture",
    "real": "Systems & Architecture",
    "name": "School of Architecture",
    "desc": "Design rituals for systems that endure across dimensions of scale, time, and team boundaries.",
    "spells": [
      {
        "name": "Cross-Domain Analogy",
        "skill": "cross-domain-analogy-generator",
        "effect": "Generate cross-domain analogies — break fixation by mapping problem structures to foreign fields (biology, music, traffic) and transferring insights.",
        "status": "—"
      },
      {
        "name": "Everything-as-Code Conceptualizer",
        "skill": "everything-as-code-conceptualizer",
        "effect": "Codify messy human problems as pseudocode to reveal hidden assumptions, missing decisions, and edge cases.",
        "status": "—"
      },
      {
        "name": "Feature Architecture",
        "skill": "feature-architecture",
        "effect": "One rule set for three moments: plan where files live before writing, review completed work, and audit the repo as a living system.",
        "status": "—"
      },
      {
        "name": "Release It! Stability Patterns",
        "skill": "release-it-stability",
        "effect": "Circuit breakers, bulkheads, timeouts, load shedding, steady-state hygiene for production failure modes.",
        "status": "—"
      },
      {
        "name": "Security Review Protocol",
        "skill": "security-review-protocol",
        "effect": "4-phase security review fusing STRIDE, hazard analysis, LLM vuln audit, and expanded threat-modeling guidance.",
        "status": "—"
      },
      {
        "name": "System Architecture Audit for AI Agents",
        "skill": "system-architecture-audit",
        "effect": "4-phase audit fusing Thinking in Systems, DDD, DDIA, and Release It. Reveals structural problems before they cascade.",
        "status": "—"
      },
      {
        "name": "Thinking in Systems",
        "skill": "thinking-in-systems-state-machine",
        "effect": "Model stocks, flows, delays, leverage points, and blast radius before touching the system.",
        "status": "—"
      },
      {
        "name": "Vibe Coding Security Hardening",
        "skill": "vibe-coding-security-hardening",
        "effect": "Hardening checklist for vulnerabilities LLMs reliably introduce: exposed secrets, missing RLS, broken auth, injection flaws, insecure defaults.",
        "status": "—"
      }
    ]
  },
  {
    "id": "orchestration",
    "real": "Agent Orchestration",
    "name": "School of Confluence",
    "desc": "Incantations for orchestrating multiple agents, sharing reasoning memory, and coordinating parallel workstreams.",
    "spells": [
      {
        "name": "Monte Carlo Tree Search for Agents",
        "skill": "monte-carlo-tree-search",
        "effect": "Allocate search effort to branches that earn it through probes and scoring.",
        "status": "—"
      },
      {
        "name": "Octopus",
        "skill": "octopus",
        "effect": "Coordinate parallel sub-agents with bounded concurrency — define shared contracts, delegate with auto-healing arms, retract on failure.",
        "status": "—"
      },
      {
        "name": "Pre-Flight Intent Verification",
        "skill": "pre-flight-intent-verification",
        "effect": "Surface the critical assumption, crystallize intent into testable spec, ground facts before acting.",
        "status": "—"
      },
      {
        "name": "Scout",
        "skill": "scout",
        "effect": "Scout context — a fast sub-agent reads files and returns only distilled relevant context, saving tokens and reducing distraction for the main model. Use when the codebase is large, you need scoped findings rather than raw file dumps, or the main task needs file context you don't already have.",
        "status": "—"
      },
      {
        "name": "Sub-Agent Composer",
        "skill": "subagent-composer",
        "effect": "Compose high-context sub-agent briefs that eliminate first-pass failures.",
        "status": "—"
      },
      {
        "name": "Sub-Agent Laws",
        "skill": "subagent-laws",
        "effect": "Standing behavioral constraints every sub-agent must follow. Enforce scope discipline, test integrity, and communication standards.",
        "status": "—"
      }
    ]
  },
  {
    "id": "software-development",
    "real": "Software Development",
    "name": "School of Crafting",
    "desc": "Practical incantations for building, renaming, searching through, and shipping code.",
    "spells": [
      {
        "name": "1. Run existing tests",
        "skill": "llm-pre-push-review",
        "effect": "Checklist and protocol for catching systematic LLM coding failures: overcorrection, hallucinated logic, silent vulnerabilities, missing edge cases.",
        "status": "—"
      },
      {
        "name": "API Surface Anchoring",
        "skill": "api-surface-anchoring",
        "effect": "Verify every external API call against current docs to prevent hallucinated APIs.",
        "status": "—"
      },
      {
        "name": "Codebase Divide-and-Conquer Search",
        "skill": "codebase-divide-conquer-search",
        "effect": "Divide a large codebase into summary-ranked zones and conquer each with a parallel sub-agent. Find code by behavior, not by name.",
        "status": "—"
      },
      {
        "name": "Coordinated Change",
        "skill": "coordinated-change",
        "effect": "Ensure consistency when a fix or feature requires touching 2+ files that must stay consistent.",
        "status": "—"
      },
      {
        "name": "Git Surgery",
        "skill": "git-surgery",
        "effect": "Recover from local git disasters: detached HEAD, botched rebase, accidental commits, merge conflicts.",
        "status": "—"
      },
      {
        "name": "Lint Battalion",
        "skill": "lint-battalion",
        "effect": "Batch-process 50+ linter errors as a bulk remediation problem, not 50 separate decisions.",
        "status": "—"
      },
      {
        "name": "Review Ladder Plus",
        "skill": "review-ladder-plus",
        "effect": "Multi-agent code review ladder for production-grade QA: security, auth, data, concurrency.",
        "status": "—"
      },
      {
        "name": "Verified Code Synthesizer",
        "skill": "verified-synthesize",
        "effect": "Verify code correctness through formal Dafny specifications — given a natural language spec, produce provably correct code with pre/postconditions and loop invariants. Use for critical bugs in security, memory safety, or financial calculations; pre-refactor spec locking; or API contracts across module boundaries.",
        "status": "—"
      },
      {
        "name": "Verify Before Integrate",
        "skill": "verify-before-integrate",
        "effect": "Verify the actual system behavior rather than matching abstract terminology when integrating research or external docs.",
        "status": "—"
      }
    ]
  },
  {
    "id": "execution",
    "real": "Execution & Improvement",
    "name": "School of Execution",
    "desc": "Rituals for solving problems, executing plans, and improving systems over time.",
    "spells": [
      {
        "name": "Intent Specification Protocol",
        "skill": "intent-specification-protocol",
        "effect": "Crystallize vague coding requests into precise, testable specifications before writing any code. Prevents the Intent-Behavior Mirroring Effect.",
        "status": "—"
      },
      {
        "name": "Iterative Spec Authoring",
        "skill": "iterative-spec-authoring",
        "effect": "Author a detailed technical spec grounded in research, refine through up to 3 judge-LLM review cycles, then present to the user for final approval.",
        "status": "—"
      },
      {
        "name": "Legacy Rescue Protocol",
        "skill": "legacy-rescue-protocol",
        "effect": "Characterize legacy behavior, create seams, then transform in bounded slices with anti-loop protection.",
        "status": "—"
      },
      {
        "name": "PDCA / Shewhart Cycle",
        "skill": "pdca-deming",
        "effect": "Improve a process through a measurement-anchored cycle: plan with a measurable prediction, do, check actual vs predicted, then standardize or escalate. Standardize only what the check confirmed.",
        "status": "—"
      },
      {
        "name": "Split Large Files — Boundary-Driven Extraction Protocol",
        "skill": "split-large-files",
        "effect": "Split large files along change boundaries, not line counts. Investigate before extracting, require strong architectural signals.",
        "status": "—"
      },
      {
        "name": "Summarize — Emergency Stop + Handoff Report",
        "skill": "summarize",
        "effect": "Emergency stop + perfect handoff report so the next agent loses nothing.",
        "status": "—"
      },
      {
        "name": "Trajectory Guard — Detect and Recover from Failure Spirals",
        "skill": "trajectory-guard",
        "effect": "Detect agent failure spirals — repetitive loops, specification drift, and stuck trajectories — and forcibly redirect strategy.",
        "status": "—"
      }
    ]
  },
  {
    "id": "judgment-and-routing",
    "real": "Judgment & Decision-Making",
    "name": "School of Judgment",
    "desc": "Incantations for routing decisions, weighing tradeoffs, and routing problems to the right approach.",
    "spells": [
      {
        "name": "Advocatus Diaboli",
        "skill": "advocatus-diaboli",
        "effect": "Stress-test a proposal against a separate adversarial sub-agent to break anchoring.",
        "status": "—"
      },
      {
        "name": "Cognitive Bias Checklist",
        "skill": "cognitive-bias-checklist",
        "effect": "Explicit checklist to catch bias contamination before finalizing slow-mode recommendations.",
        "status": "—"
      },
      {
        "name": "Counterfactual Policy Testing",
        "skill": "counterfactual-policy-testing",
        "effect": "Compare a decision against null, opposite, and partial counterfactuals before committing.",
        "status": "—"
      },
      {
        "name": "Evidence Grounding",
        "skill": "evidence-grounding",
        "effect": "Resolve every load-bearing observation against current evidence before acting: freshness checks on what you read, an early falsifying probe after the first edit, and receipts on every progress claim.",
        "status": "—"
      },
      {
        "name": "Explore vs Exploit",
        "skill": "explore-vs-exploit-state-machine",
        "effect": "Explicit explore/exploit protocol: frame the decision, budget the search, explore with purpose, stop deliberately, act when search stops earning its keep.",
        "status": "—"
      },
      {
        "name": "Failure Swarm",
        "skill": "failure-swarm",
        "effect": "Swarm 3-5 critic personas over a spec to surface failure modes pre-implementation. User-invoked; type `/failure-swarm`.",
        "status": "—"
      },
      {
        "name": "First Principles Thinking",
        "skill": "first-principles",
        "effect": "Decompose to axiomatic foundations and reason upward from what must be true.",
        "status": "—"
      },
      {
        "name": "Future Mortem",
        "skill": "future-mortem",
        "effect": "After code is written, assume it will cause future pain and work backward to find what will bite: debt with interest, extension traps, hidden assumptions, maintenance memory, time bombs, and upgrade cliffs. Use when implementation is done and the agent must surface what the code will cost the project later.",
        "status": "—"
      },
      {
        "name": "Occam's Razor",
        "skill": "occams-razor",
        "effect": "Favor the simplest sufficient explanation or solution. Try the simplest thing that fits the evidence before escalating.",
        "status": "—"
      },
      {
        "name": "Pre-Mortem",
        "skill": "pre-mortem-state-machine",
        "effect": "Validate a plan before execution: assume failure has already happened, generate specific failure narratives, rank them, and adjust the plan.",
        "status": "—"
      },
      {
        "name": "Recognition-Primed Triage",
        "skill": "recognition-primed-triage-state-machine",
        "effect": "Gated incident-response protocol: recognize the pattern, simulate the first action, act within scope, reassess, hand off.",
        "status": "—"
      },
      {
        "name": "Reference Class Forecasting",
        "skill": "reference-class-forecasting",
        "effect": "Anchor to similar past projects before reasoning from the specifics.",
        "status": "—"
      },
      {
        "name": "Steelmanning for AI Agents",
        "skill": "steelmanning",
        "effect": "Construct the strongest opposing case before committing to a recommendation.",
        "status": "—"
      },
      {
        "name": "Thoroughness Check (ETTO)",
        "skill": "thoroughness-check-etto-state-machine",
        "effect": "Gate task execution by the Efficiency-Thoroughness Trade-Off: classify rigor 1-5, meet the evidence bar, act within the mode, validate to match.",
        "status": "—"
      },
      {
        "name": "Unsafe Control Actions / Hazard Analysis",
        "skill": "unsafe-control-actions-hazard-analysis",
        "effect": "Analyze how a control action could become unsafe before recommending or performing it.",
        "status": "—"
      }
    ]
  },
  {
    "id": "testing",
    "real": "Testing & Measurement",
    "name": "School of Measurement",
    "desc": "Empirical measurement of skill effectiveness and code quality.",
    "spells": [
      {
        "name": "E2E Cross-Check Protocol",
        "skill": "e2e-crosscheck",
        "effect": "Bidirectional audit between E2E test selectors/assertions and source code. Reconciles every test identifier, text assertion, and navigation route.",
        "status": "—"
      }
    ]
  },
  {
    "id": "output-quality",
    "real": "Output Quality",
    "name": "School of Refinement",
    "desc": "Incantations for improving, verifying, and stress-testing output before it ships.",
    "spells": [
      {
        "name": "Documentation Craft",
        "skill": "documentation-craft",
        "effect": "Multi-phase pipeline from outline to verified explanation, audience-driven and source-grounded.",
        "status": "—"
      },
      {
        "name": "Rubric Gate",
        "skill": "rubric-gate",
        "effect": "Write a rubric of binary done-criteria before implementing, then gate on it: every criterion shows PASS with evidence before work ships.",
        "status": "—"
      },
      {
        "name": "Self Verify Pipeline",
        "skill": "self-verify-pipeline",
        "effect": "Escalating verification chain of bounded revision, claim decomposition, and tool-grounded critique.",
        "status": "—"
      }
    ]
  },
  {
    "id": "debugging",
    "real": "Debugging",
    "name": "School of Remediation",
    "desc": "Incantations to banish bugs and restore order to broken code.",
    "spells": [
      {
        "name": "Debug Issue",
        "skill": "debug-issue",
        "effect": "Force the reproduce → isolate → fix → verify cycle. Graph-powered code navigation traces issues through the system along dataflow edges. Use when the bug spans multiple modules or services, the crash site isn't the cause, or state diverges across an async boundary.",
        "status": "—"
      },
      {
        "name": "Debug Subagent",
        "skill": "debug-subagent",
        "effect": "Gate debugging behind a dedicated subagent — consult it before any code edit. Wraps debugger complexity behind natural-language queries. Use when the fix is not immediately obvious from the error, for multi-file bugs needing runtime state inspection, or when static analysis hasn't revealed the root cause.",
        "status": "—"
      },
      {
        "name": "Debug-to-Fix Pipeline",
        "skill": "debug-to-fix-pipeline",
        "effect": "6-phase pipeline that increases evidence quality each phase while cutting token waste: context → hypothesis → instrument → capture → purify → patch → verify.",
        "status": "—"
      },
      {
        "name": "Environment Recovery",
        "skill": "environment-recovery",
        "effect": "Diagnose and fix broken development environments — missing tools, wrong versions, corrupted caches, full disks, permission drift, and dependency hell. The skill every other debugging skill assumes.",
        "status": "—"
      },
      {
        "name": "Escalation Ladder",
        "skill": "escalation-ladder",
        "effect": "Structured protocol for when an agent is stuck — escalating from self-recovery to user collaboration to full retreat. Fills the gap between trajectory-guard (detects stuck) and summarize (bails out).",
        "status": "—"
      },
      {
        "name": "Minimal Reproduction",
        "skill": "minimal-reproduction",
        "effect": "Write the smallest possible test that demonstrates the bug, then use it as ammunition for debugging.",
        "status": "—"
      },
      {
        "name": "Network / API Debugging",
        "skill": "network-api-debugging",
        "effect": "Diagnose and fix network and API failures — CORS, auth token issues, rate limiting, redirect chains, WebSocket drops, and HTTP request/response mismatches.",
        "status": "—"
      },
      {
        "name": "Specter",
        "skill": "specter",
        "effect": "Abduce the bug — generate competing hypotheses, locate code by structural relationship, then disconfirm until one survivor remains. Use when the crash site is not the cause, the bug is 'weird,' or your first instinct is suspect.",
        "status": "—"
      },
      {
        "name": "Time-Traveling Debugger",
        "skill": "time-traveling-debugger",
        "effect": "When a bug occurs, record a deterministic execution trace forward, then replay it in reverse from the crash point to find the exact line where state first diverged.",
        "status": "—"
      }
    ]
  },
  {
    "id": "research",
    "real": "Research",
    "name": "School of Research",
    "desc": "Skills related to research.",
    "spells": [
      {
        "name": "Effective Web Search",
        "skill": "effective-web-search",
        "effect": "Web search discipline for technical research. Official-docs-first, version-aware, full GitHub issue follow-through.",
        "status": "—"
      }
    ]
  },
  {
    "id": "development",
    "real": "Development & Tooling",
    "name": "School of Tools",
    "desc": "Tooling, utilities, and workflows for development tasks.",
    "spells": [
      {
        "name": "Unit Test Debugging",
        "skill": "unit-test-debugging",
        "effect": "Systematic workflow for fixing failing unit tests by first determining whether the tests or the code under test are the source of truth.",
        "status": "—"
      }
    ]
  }
];

export default schools;
